### PR TITLE
Remove ignored errors in phpstan which have been resolved upstream

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

https://github.com/symfony/symfony/pull/31903 was released.

### CODE REVIEW

**Comment by teohhanhui** [comment]
Hmm... I'm not sure why this is still failing.

But this is OK: https://phpstan.org/r/4883b3fc-fd99-4bcd-b0f8-0426df527bec

@ondrejmirtes Perhaps you have an idea of what's going on?

**Comment by ondrejmirtes** [comment]
Please check out what type each expression has:

```
$client = static::createClient();
$client === 'aaa';
$client->getResponse() === 'aaa';
```

A rule starting with `Strict comparison between ...` will tell you what the type is. There's no magic, PHPStan just reads native typehints and phpDocs, so you  can figure that out.

**Comment by teohhanhui** [comment]
Okay, so the problem seems to me like `symfony/framework-bundle` 4.2 is not forward compatible with `symfony/http-kernel` 4.3 :disappointed:

**Comment by teohhanhui** [comment]
Will be fixed by https://github.com/symfony/symfony/pull/32213

In the meantime, we can already remove these ignored errors on `master`.

**Comment by teohhanhui** [comment]
Obsoleted by #2925

**Pull request closed without merging**
