### PR TITLE
fix(metadata): no deprecation when elasticsearch is null

### PR DESCRIPTION
**Pull request by dannyvw**
| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Tickets       | #... 
| License       | MIT
| Doc PR        | api-platform/docs#... 

Related to https://github.com/api-platform/core/pull/5450. Now fixed for non graphql operations.

### CODE REVIEW

**Comment by soyuka** [comment]
Looks like the Behat CI for ES in unhappy witht he changes

**Comment by dannyvw** [comment]
@soyuka The provider is not set anymore https://github.com/api-platform/core/blob/main/src/Elasticsearch/Metadata/Resource/Factory/ElasticsearchProviderResourceMetadataCollectionFactory.php#L63. I could add this in the testcases, but not sure if that is the right way.

**Comment by soyuka** [comment]
thanks @dannyvw !

**Comment by soyuka** [comment]
My bad I reverted it was still red. I cannot reopen, maybe we can discuss this at #5497

**Comment by dannyvw** [comment]
This pipeline is indeed red and it is something else than #5497

**Pull request merged**
