### PR TITLE
Rebuild the container when an entity is modified

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Automatically rebuild the container if an entity is modified.

### CODE REVIEW

**Comment by teohhanhui** [comment]
:-1:

If this is proper, then it should be done in DoctrineBundle.

**Comment by dunglas** [comment]
It has nothing to do with Doctrine. It is applicable even if you use another persistence system.
Routes of the API depend of resources metadata. If annotations are used, routes change when entity classes are modified. This patch improve the DX: doing a cache:clear each time an `@ApiResource` annotation is modified isn't necessary anymore. It's common in Symfony to do this (a similar trick is used for controller annotations).

**Comment by teohhanhui** [comment]
Is the `Entity` directory used when Doctrine is not used?

**Comment by dunglas** [comment]
Yes.

**Comment by teohhanhui** [comment]
Okay, I get what you mean now...

**Comment by dunglas** [comment]
https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L133

**Pull request merged**
