### PR TITLE
Convert the route prefix attribute name to snake case

### PR DESCRIPTION
**Pull request by meyerbaptiste**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Indeed, all our attributes use snake case except this one.

cc @Toflar

### CODE REVIEW

**Comment by Toflar** [comment]
It's just a BC break for the ones already using it.

**Comment by meyerbaptiste** [comment]
No BC break, this feature is not released yet!

**Comment by Toflar** [comment]
Ah, I thought it was :D

**Comment by dunglas** [comment]
Thanks @meyerbaptiste

**Pull request merged**
