### PR TITLE
hotfix #537: Change @Resource annotation to @ApiResource

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #537
| License       | MIT

This is resolving the problem of resource being a soft reserved word in php7

### CODE REVIEW

**Comment by dunglas** [comment]
Thanks! Can you update the doc as accordingly?

**Comment by dunglas** [comment]
I propose to also rename `@Property` to `@ApiProperty` for coherence. Do you agree @api-platform/core-team @Simperfit?

**Comment by theofidry** [comment]
Makes sense 👍

**Comment by Simperfit** [comment]
I will do it and update the doc

**Pull request merged**
