### PR TITLE
Add EmbeddedNormalizer

### PR DESCRIPTION
**Pull request by teohhanhui**
Related: #166 #181

Not sure if this is still relevant since #375 was merged...

### CODE REVIEW

**Comment by teohhanhui** [comment]
@dunglas Will rebase if this is still useful...

**Comment by dunglas** [comment]
@teohhanhui it should work without the need for a new normalizer in `master` now thanks to #375. Can you try?

**Comment by teohhanhui** [comment]
That's great! I'll try upgrading soon...

**Comment by dunglas** [comment]
#422 fixes the last problem related to this PR (and it proves it works for dates, but it is a generic solution).

**Comment by sroze** [comment]
@teohhanhui can you try with master? By the way, without tests, there's almost no chances that we merge it :)

**Comment by teohhanhui** [comment]
@dunglas  @sroze It's still a problem when using Doctrine Embeddables. They should be able to be marked as `@ApiResource` (for the whole set of features that come with that).

Also, currently the normalization / denormalization chain of `ItemNormalizer` stops when a Doctrine Embeddable is encountered (because it's just treated as a normal object and handled by `ObjectNormalizer`). This might not be a problem if #528 is implemented (our current process is inherently flawed because it depends on an unbroken chain from the top).

**Pull request closed without merging**
