### PR TITLE
fix(doctrine): doctrine/orm:^3.0 support

### PR DESCRIPTION
**Pull request by soyuka**
#6156

### CODE REVIEW

**Comment by soyuka** [comment]
@fabpot can confirm that sf dev tests are good to go, is it possible to release a new patch version (at least 6.4 and 7.0) ?

**Comment by fabpot** [comment]
@soyuka Releases done :)

**Comment by julienhouyet** [comment]
Hello, I've updated to code version to 3.2.16 (and doctrine/orm to 3.1.0)but unfortunately I still have the same problem: 

...Doctrine\NMapping".did you forget a "use" declaration for another namespace?

I downgraded and it works again:

  - Downgrade api-platform/core (v3.2.16 => v3.2.15) : Archive extraction
  - Install doctrine/common (3.4.3) : Extract archive
  - Decommissioning doctrine/orm (3.1.0 => 2.19.0) : Archive extraction
 
Have a nice day :)

**Comment by soyuka** [comment]
I don't understand your message, please open a new issue with a stack trace, thanks!

**Pull request merged**
