### PR TITLE
Revert "fix skipped data persisters on persist"

### PR DESCRIPTION
**Pull request by dunglas**
Reverts api-platform/core#2064

### CODE REVIEW

**Comment by bendavies** [comment]
what's the reason @dunglas ?

**Comment by bendavies** [comment]
i see: https://github.com/api-platform/docs/issues/540#issuecomment-405945358

**Comment by ragboyjr** [comment]
@dunglas is there any reason this change wasn't done for the remove method of the ChainDataPersister?

**Comment by antograssiot** [comment]
It has been done but maybe not released yet https://github.com/api-platform/core/pull/2223

**Pull request merged**
