### PR TITLE
Case insensitive search filter

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | https://github.com/dunglas/doc/pull/5

I refactored the code a bit by removing nested conditions, hope that's ok.

### CODE REVIEW

**Comment by sroze** [comment]
LGTM :+1:

**Comment by dunglas** [comment]
Thank you @soyuka

**Comment by teohhanhui** [comment]
I don't understand why the case-sensitivity should be applied at the filter-level instead of per-property.

**Comment by teohhanhui** [comment]
Also, what of the collations where the matching is already case-insensitive in the first place (like what is most commonly used in MySQL - `utf8_unicode_ci` or `utf8mb4_unicode_ci`)? We might want to add a note somewhere...

**Comment by soyuka** [comment]
+1 @teohhanhui can you add this to the docs?

About the property we discussed it in the PR on 1.x, because it's reset [here](https://github.com/api-platform/core/pull/548/commits/c638d3d6897f631cf6a5c524f207e608b4fc837a#diff-77ec54980605d6062780fcd93ba31c64R122) and to avoid lots of repetition to pass the flag to the caseWrap function, I think it's better to keep the instance property.

**Pull request merged**
