### PR TITLE
Add an option to disable query parameter validation

### PR DESCRIPTION
**Pull request by norkunas**
| Q             | A
| ------------- | ---
| Branch?       | main
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | https://github.com/api-platform/docs/pull/1329

Query parameter validation can be costly if you are not using any required filters, so we should have an option to disable it.
If you think that this is a good addition, I'll add some tests.

### CODE REVIEW

**Comment by alanpoulain** [comment]
Is it really? Maybe a Blackfire profile would help to see if it's the case.

**Comment by norkunas** [comment]
> Is it really? Maybe a Blackfire profile would help to see if it's the case.

When filters depends on the dynamic structure which loads from external storages then yes.

**Comment by alanpoulain** [comment]
> > Is it really? Maybe a Blackfire profile would help to see if it's the case.
> 
> When filters depends on the dynamic structure which loads from external storages then yes.

It's an edge case, isn't it? If it is, I think the best approach is to decorate the listener instead of having a specific and not used much configuration parameter.

**Comment by norkunas** [comment]
> > > Is it really? Maybe a Blackfire profile would help to see if it's the case.
> > 
> > When filters depends on the dynamic structure which loads from external storages then yes.
> 
> It's an edge case, isn't it? If it is, I think the best approach is to decorate the listener instead of having a specific and not used much configuration parameter.

Why to run some validations when you don't use them at all? IIRC @soyuka in slack said that it's by default should not be enabled at all.

**Comment by norkunas** [comment]
Also read/deserialize/serialize/validate can be disabled so why not query param validator?

**Comment by antograssiot** [comment]
Didn't checked the PR but it is indeed costly and should be opt-in, totally 👍, we've discovered that on your project too and discussed it with @soyuka

**Comment by alanpoulain** [comment]
OK! You can add some tests then @norkunas.

**Comment by norkunas** [comment]
Added some tests.

**Review by alanpoulain — APPROVED** [review]
LGTM. Don't forget the CHANGELOG and the documentation.

**Comment by norkunas** [comment]
Added some docs for this PR.

**Comment by alanpoulain** [comment]
Nice work. Thank you @norkunas.

**Pull request merged**
