### PR TITLE
Add a script to update Swagger UI

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Easier maintenance for us, but still as easy than now for people to use the bundle.
Btw every major Symfony bundle I checked commit their JS deps (Sonata Admin, EasyAdmin, NelmioApiDoc).

### CODE REVIEW

**Comment by teohhanhui** [comment]
> Btw every major Symfony bundle I checked commit their JS deps (Sonata Admin, EasyAdmin, NelmioApiDoc)

That's the problem when you have (mostly) backend developers... :stuck_out_tongue:

**Comment by dunglas** [comment]
The main problem is that's difficult to use NPM with the `Resources/public` convention.

**Comment by soyuka** [comment]
+1 about your statement and if you want it bundled I don't see any other solution that would not require the full node-npm-bower stack.

**Comment by teohhanhui** [comment]
I do not believe that we should use `npm`, no.

This should really be solved in swagger-api/swagger-ui#2310

**Comment by dunglas** [comment]
Even if Swagger UI becomes available on Packagist, it will not help: files will not be copied in a `Resources/public` directory.

**Comment by teohhanhui** [comment]
@dunglas Isn't that something we can take care of in our bundle?

**Comment by teohhanhui** [comment]
Do you think [Puli](http://docs.puli.io/en/latest/) covers our use case?

**Comment by teohhanhui** [comment]
Or more likely just a Composer post-install script to copy the assets.

**Comment by soyuka** [comment]
> Or more likely just a Composer post-install script to copy the assets.

I proposed that before and it was rejected as it'd require some external tools.

**Comment by dunglas** [comment]
Another option is to display an error asking the user to run `npm install` if assets aren't installed.
It's not really adapted for Swagger UI (I want it to be available without extra steps) but it can be a good alternative for projects having more JS dependencies.

**Comment by teohhanhui** [comment]
@dunglas:
> Another option is to display an error asking the user to run npm install if assets aren't installed.

I don't like that as it's not good for Docker. It'd mean having another Docker container just to do `npm install`.

**Pull request merged**
