### PR TITLE
Removing google fonts from swagger ui

### PR DESCRIPTION
**Pull request by eerison**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       |  [1346](https://github.com/api-platform/api-platform/issues/1346)
| License       | MIT

### CODE REVIEW

**Comment by teohhanhui** [comment]
This is not it. This breaks the styling. We want to maintain the same fonts, perhaps loaded locally or embedded as data URI.

**Comment by dunglas** [comment]
As this font is a free one, you can download it from here https://fonts.google.com/specimen/Titillium+Web and copy it in this Git repository.

**Comment by eerison** [comment]
Hi @dunglas and @teohhanhui 

Sorry for that!

@dunglas do you mean add this [font](https://fonts.google.com/specimen/Titillium+Web) on project and get from that font?

**Comment by soyuka** [comment]
> @dunglas do you mean add this font on project and get from that font?

Yes and use it locally

**Comment by alexislefebvre** [comment]
This was done in #4112.

**Pull request closed without merging**
