### PR TITLE
Fold Behat output in Travis

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by teohhanhui** [comment]
I think currently the main problem is that it's very hard to see the progress of running Behat features... Perhaps a simple progress indicator might help.

**Comment by dunglas** [comment]
@teohhanhui do you know if Behat supports this? Would be cool!

**Comment by Simperfit** [comment]
There is something like phpunit in behat : 

```bash
 $ vendor/bin/behat --format=progress
...................................................................... 70
...................................................................... 140
...................................................................... 210
...............

50 scenarios (50 passed)
225 steps (225 passed)
0m23.80s (72.24Mb)

```

**Comment by dunglas** [comment]
@Simperfit great! Just updated the PR.

**Comment by teohhanhui** [comment]
Idk... We're calling the `behat` command in a loop. We'd probably need something fancier like in symfony/symfony...

**Comment by teohhanhui** [comment]
Let's plagiarize lol...

**Comment by dunglas** [comment]
We call in in a loop only for the coverage. The current patch is good enough WDYT?

**Comment by teohhanhui** [comment]
Looks like it has sped up the Travis build tremendously. Yay!

**Pull request merged**
