### PR TITLE
Deprecate xml operations configuration and provide new way to make it…

### PR DESCRIPTION
**Pull request by soyuka**
… possible to disable all operations

----

<details>
<summary>Git things</summary>
 
Cleaning #993 @sawmurai 

To do so, I did:

`git rebase -i [commit sha preceding your first commit]`, I then changed your multiple commits to `fixup` (you can also move the commits there to the latest):

rebase

Then every time it has a conflict, edit + fix conflict. Then `git add conflicting files` + `git rebase --continue`.

You end up with 1 commit and no weird things in github usually mean it's clean :).
</details>

### CODE REVIEW

**Comment by sawmurai** [comment]
Can we just use this PR?

**Comment by soyuka** [comment]
This is up to date @dunglas feel free to merge!

Thanks @sawmurai for the work!

**Comment by dunglas** [comment]
After a second though, it's not a good idea to introduce a deprecation in a patch release. I prefer merging in master. WDYT?

**Comment by soyuka** [comment]
@dunglas yeah agreed

**Comment by dunglas** [comment]
Can you rebase against master?

**Comment by soyuka** [comment]
I've done a new commit (or we need to merge 2.0 in master before I rebase :p, I still have a copy of the old commit which accounts @sawmurai work).

**Comment by dunglas** [comment]
Thank you very much @halfdan (and @soyuka of course)

**Comment by soyuka** [comment]
And @meyerbaptiste @teohhanhui for the great code review!

**Comment by sawmurai** [comment]
Close, I am @sawmurai ;) But you are very welcome :)

**Pull request merged**
