### PR TITLE
Configure formats provider interface autowiring alias

### PR DESCRIPTION
**Pull request by norkunas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by antograssiot** [comment]
@dunglas I think that we should promote `OperationAwareFormatsProviderInterface` instead

**Comment by norkunas** [comment]
Missed that interface somehow :)

**Comment by norkunas** [comment]
Switched to `OperationAwareFormatsProviderInterface`

**Comment by soyuka** [comment]
thanks @norkunas !

**Pull request merged**
