### PR TITLE
fix: indexing relations resources IRIs in normalization

### PR DESCRIPTION
**Pull request by cedvan**
| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | https://github.com/api-platform/core/issues/3168
| License       | MIT

Hi,

Currently all the IRIs of the resource relations being normalized are indexed in the cache.

However only relationship IRIs that are normalized and nested should be indexed.

This correction allows to considerably lighten the `Cache-Tags` header in the case of a fullREST hypermedia API and thus repair the maximum header size problem, especially with Varnish

Maybe must apply this fix to current 2.6 ?

### CODE REVIEW

**Comment by dunglas** [comment]
Even if they aren't nested but only referenced, we must invalidate the document containing the reference to handle because the related resource may be deleted.

**Comment by cedvan** [comment]
I understand, but orm relation prevents deleting an entity with a referenced relation, right?

**Comment by cedvan** [comment]
So to delete entity A, I have to update entities X, Y, Z ... which references it to delete the relation with A and then I can delete my entity A. These updates will purge the cache of these entities X, Y, Z ...

**Comment by cedvan** [comment]
What case do I forget that can possibly be different?

**Comment by cedvan** [comment]
Maybe this problem can be effective in non-owner reverse relationships, right?

**Comment by cedvan** [comment]
So maybe we just need to add IRIs for nonn-owner related entities?

**Comment by cedvan** [comment]
Or maybe just change the purge system and add a specific purge when deleting an A entity on all documents from X, Y, Z ... entities that have at least one inverse relationship to A.

Deletion is rare enough to tolerate a complete purge of an entity's documents. Especially since we use a lot of solf delete today

**Comment by dunglas** [comment]
This part isn't coupled with the ORM (you can use it with any data provider, even if you don't use an ORM). By default, we prefer to be as exact as possible and to let users add "risky" (not generic) optimizations in their own code base by replacing or decorating the built-in services.

**Comment by cedvan** [comment]
D'accord. Une autre solution pour résoudre le problème de taille d'en-tête ? J'ai une grande API hypermédia fullREST, et la taille de l'en-tête est vraiment trop grande :/.

**Comment by dunglas** [comment]
Did you try this https://api-platform.com/docs/extra/troubleshooting/#upstream-sent-too-big-header-while-reading-response-header-from-upstream-nginx-502-error?

**Comment by cedvan** [comment]
Yes, but after receive "Error 503 Backend fetch failed" instead of "502"

**Comment by cedvan** [comment]
Ok, I solve 503 problem by add `-p http_resp_size=__k -p http_resp_hdr_len=__k` to varnish command. Maybe necessary add this to documentation ?

**Pull request closed without merging**
