### PR TITLE
use strtolower for operationNames in DocumentationNormalizer

### PR DESCRIPTION
**Pull request by WhiteRabbitDE**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | -
| Fixed tickets | #3025, #3022
| License       | MIT
| Doc PR        | -

It is a pretty minor thing, still ended up in an unexpected result ( see #3022 )

### CODE REVIEW

**Comment by teohhanhui** [comment]
Sorry, I'm not sure this is the right fix. Which part is using the `operationId` in the first place?

**Comment by WhiteRabbitDE** [comment]
> Sorry, I'm not sure this is the right fix. Which part is using the `operationId` in the first place?
I hope i got your question right.

The operationId is used in the path item object and is used to uniquely identify the operation. As described in #3025 you could now end up in an operationId like "pOSTAnswerCollection" because only the first letter of "POST" is transformed to lowercase. This happens when you use all Uppercase letters in your Annotations  ` collectionOperations={"POST"},`

**Comment by teohhanhui** [comment]
```
Uncaught PHP Exception ApiPlatform\Core\Exception\RuntimeException: "The operation "GETQuizCollection" cannot be found in the Swagger specification." at D:\xampp\htdocs\quizz\quizz-api\vendor\api-platform\core\src\Bridge\Symfony\Bundle\Action\SwaggerUiAction.php line 180
```

This is the actual bug. We should fix it here.

**Comment by soyuka** [comment]
@teohhanhui the problem here is that the operation will end up being `pOST...` instead of `POST...`. Lowercasing the whole method will definitely do the trick and it's definitely better to have `post` then `pOST` no?

**Comment by teohhanhui** [comment]
And `postCustom` will become `postcustom`. Not good. As we've both agreed upon, this is the wrong use case. Don't use UPPERCASE for operation names.

**Comment by soyuka** [comment]
Mhh yeah you're right, and I just got the "thing we should fix":

```
Uncaught PHP Exception ApiPlatform\Core\Exception\RuntimeException: "The operation "GETQuizCollection" cannot be found in the Swagger specification." at D:\xampp\htdocs\quizz\quizz-api\vendor\api-platform\core\src\Bridge\Symfony\Bundle\Action\SwaggerUiAction.php line 180
```

It should look for `gETQuizCollection` :p

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/3025#issuecomment-532184300 sorry about the miscomprehension on my end I should've thought that a bit more.

**Pull request closed without merging**
