### PR TITLE
Exclude static methods in AnnotationPropertyNameCollectionFactory

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by teohhanhui** [comment]
Why?

**Comment by soyuka** [comment]
> Why?

I asked myself the exact same thing, any reason?

**Comment by dunglas** [comment]
See here: https://github.com/symfony/symfony/pull/21331#issuecomment-274442560

**Comment by dunglas** [comment]
It's not really mandatory here (because it's weird to add an annotation on a static method), but it should be handled any way for the sake of consistency.

**Pull request merged**
