### PR TITLE
[Subresource] Fix subresource filters attributes resolving

### PR DESCRIPTION
**Pull request by ahmed-bhs**
| Q             | A
| ------------- | ---
| Branch?       | 2.6
| Tickets       | #4127 #3534
| License       | MIT
 
 The problem that `filters` attribute is not taken into account neither at the level of the `OpenApiFactory`, nor at the level of the different Filter extensions.
This is due to the fact that we call the `getCollectionOperationAttribute` function regardless of the type of operation `OperationType::SUBRESOURCE` or `OperationType::COLLECTION`.
This patch allows checking the type of operation and properly retrieve the attributes related to our operation in order to finally filter the collection returned from our `subresource` operation.

_How to reproduce:_

Imagine we have an `Employee` entity related via `OneToMany` to an `EmployeeCompetence` entity.

```
resources:
    App\Entity\Competence\EmployeeCompetence:
        subresourceOperations:
            api_employees_employee_competences_get_subresource:
                method: 'GET'
                filters: [ 'employee_competence.numeric_filter', 'employee_competence.order_filter', 'employee_competence.exists_filter' ]
                normalization_context:
                    groups: [ 'employee_competence:collection:get' ]
 ```
 Before the fix, filters will not be applied, and will not even be listed. After, filters will be resolved and listed on the openApi doc.
 
 Cheers!

### CODE REVIEW

**Comment by ahmed-bhs** [comment]
I have no idea why the coverage is not satisfied ?

**Comment by ahmed-bhs** [comment]
@alanpoulain could you recheck this PR please :)

**Comment by ahmed-bhs** [comment]
@lucasgranberg great idea, less code duplication! Thank you.

**Comment by soyuka** [comment]
subresources with the ApiSubresource annotation are deprecated in 2.7 this is good work but we are not likely to merge it it may be interesting to check if this is working on the main branch (it should)

**Pull request closed without merging**
