### PR TITLE
Remove redundant type declaration of PaginatorInterface

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

```php
PaginatorInterface instanceof \Traversable
```

### CODE REVIEW

**Comment by teohhanhui** [comment]
Or is it intended? Is it beneficial to be explicit here?

**Comment by soyuka** [comment]
PaginatorInterface is a Traversable no? I'm +1 on this.

Ref recent patch on this https://github.com/api-platform/core/commit/e800eaca139d6bdbec5a70233084500195f34f58

**Comment by dunglas** [comment]
It was to be able to get autocompletion.

**Comment by teohhanhui** [comment]
If you do

```php
if ($data instanceof PaginatorInterface) {
```

then the IDE should be smart enough to deduce the fact that it is indeed a `PaginatorInterface`, and provide autocompletion accordingly, no?

**Comment by dunglas** [comment]
Thanks @teohhanhui

**Pull request merged**
