### PR TITLE
[2.4] Allow autowiring of class extending SearchFilter

### PR DESCRIPTION
**Pull request by antograssiot**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

Remove a BC break introduced in #2630

### CODE REVIEW

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/2640 related? @meyerbaptiste can we merge this?

**Comment by meyerbaptiste** [comment]
No. Did my change break the autowiring @antograssiot?

**Comment by soyuka** [comment]
I'm asking because it has been changed in the cs fixes you did in: https://github.com/api-platform/core/commit/97fa954dabd4d5d49f3dd92171ae6c677a97f50b#diff-77ec54980605d6062780fcd93ba31c64

**Comment by antograssiot** [comment]
@soyuka No #2640 is not related and on master only.
@meyerbaptiste yes it does break autowiring because the argument ha sno typehint (and it's normal as it is deprecated) but there's no default value anymore. Anyway it is a BC break IMO, it is not compliant with Symfony backward compatibility promise to remove default value of an argument in a public method

**Comment by meyerbaptiste** [comment]
> it is not compliant with Symfony backward compatibility promise to remove default value of an argument in a public method

But a default value here is a non-sense because the following argument is not optional (`IriConverterInterface $iriConverter`)...

**Comment by antograssiot** [comment]
I know/understand that it is a "non sense" to have this optional value before mandatory arguments but we can't change the argument order either. I don't have a better proposal

```
Cannot autowire service "Foo": argument "$requestStack" of method "ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter::__construct()" has no type-hint, you should configure its value explicitly.
```

**Comment by meyerbaptiste** [comment]
Ahah, yes I agree with that and your patch regarding the autowiring. Maybe the DependencyInjection component should inject `null` in this case, but that's another debate and it's not ours. 😄

**Comment by meyerbaptiste** [comment]
My bad, thx @antograssiot!

**Comment by teohhanhui** [comment]
Now it feels like we're writing code for the autowiring lol!

**Comment by teohhanhui** [comment]
Do we have a way (`_bind` or something) to let the autowiring know what to inject, without doing this weird hack in our code?

**Pull request merged**
