### PR TITLE
Remove PHP 7.1 from CI

### PR DESCRIPTION
**Pull request by alanpoulain**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by alanpoulain** [comment]
@dunglas could you remove 7.1 from required status check please?

**Comment by dunglas** [comment]
But why? We still support PHP 7.1 isn't it?

**Comment by alanpoulain** [comment]
We still support it, but it causes test issues because of the new Doctrine Inflector (BC changes and PHP > 7.1).
Also, I think it would be a good thing to drop it for 2.6 (because this version is not maintained anymore and some libs don't support it like the Doctrine ones).

**Comment by dunglas** [comment]
Can't we add a BC layer to support older versions of Doctrine Inflector? Or aren't these versions maintained? That being said, OK for me to trop support for PHP 7.1 in 2.6, but we should keep the tests for 2.5.

Btw, at some point I would like to switch from Doctrine Inflector to Symfony String).

**Comment by alanpoulain** [comment]
Yes, we can add a BC layer (that's what it has been done here: https://github.com/api-platform/core/pull/3564).
However some tests cannot be kept (mainly because the plural of `taxon` was `taxons` before 1.4 and `taxa` after). That's why I wanted to remove PHP 7.1 from the tests but keep the compatibility anyway for API Platform 2.5. But not for 2.6.

**Comment by flug** [comment]
Have you tried this? https://github.com/doctrine/inflector/issues/147
```
"conflict": {
        "doctrine/inflector": "^1.4"
    },
```

**Comment by soyuka** [comment]
let's rebase this onto master, wdyt @alanpoulain ?

**Comment by roukmoute** [comment]
> Doctrine Inflector to Symfony String

Why @dunglas?

**Comment by dunglas** [comment]
To prevent this kind of issues.

**Pull request closed without merging**
