### PR TITLE
Test with PHP 7.1

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by teohhanhui** [comment]
But why would PHP 7.1 be used with the lowest dependencies? Shouldn't we add another matrix instead?

**Comment by dunglas** [comment]
@teohhanhui it's a good idea to test the lowest version of the dependencies with the highest runtime. It maximises the probability to encounter errors because old versions of libraries are most likely the ones not support last versions of PHP.

We can add another line in the matrix but it will slow down the build for no real benefit (IMO). Does it worth it?

**Comment by teohhanhui** [comment]
> It maximises the probability to encounter errors because old versions of libraries are most likely the ones not supporting the last version of PHP.

It maximises the probability of other libraries messing up our tests, and that's not our intention. IMO The lowest dependencies test should use the lowest PHP version (if for no other reason than being realistic).

**Comment by dunglas** [comment]
It's our responsibility to set correctly the min versions to use. Symfony (and most projects I follow) uses the same strategy.

**Pull request merged**
