### PR TITLE
[DEFAULT ORDER] #1246: Support default order for a specific custom operation

### PR DESCRIPTION
**Pull request by ahmed-bhs**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tickets       |  #1321
| License       | MIT
| Doc PR        | api-platform/docs#1195

Currently, the `default-order` impact all the defined collection operations, so, it is not possible to have two different custom operations with different `default-order` configurations.

The idea is to support both, the definition of an order in a global way and also in a more specific way.

For example:
```yaml
resources:
    attributes:
        order: ["foo", "ASC"]
    App\Entity\Book:
        collectionOperations:
            get_desc:
               method: GET
               path: /books/desc
               order: ["name", "DESC"]
               normalization_context:
                    groups: ['group1']
            get_asc:
               method: GET
               path: /books/asc
               order: ["name", "ASC"]
               normalization_context:
                    groups: ['group2']
            get_another:
               method: GET
               path: /books/another
               normalization_context:
                    groups: ['group3']
```
* `order: ["name", "DESC"]` will be applied on *get_desc* operation.
* `order: ["name", "ASC"]` will be applied on *get_asc* operation.
* `order: order: ["foo", "ASC"]` will be applied on *get_another* operation.

This will allow to have a parent generic configuration and others more specific child configuration.

### CODE REVIEW

**Comment by ahmed-bhs** [comment]
@dunglas 🙋 Could please take a quick look and let me know what do you think about it!

**Review by soyuka — APPROVED** [review]
:+1: on the patch I just need to check with @dunglas if we can consider this a bug fix

**Comment by dunglas** [comment]
To le it's good as a new feature! Thanks for working on this @ahmed-bhs.

**Comment by soyuka** [comment]
Thanks @ahmed-bhs

**Pull request merged**
