### PR TITLE
fix(patch): Fix PATCH oneToMany

### PR DESCRIPTION
**Pull request by ilicmsreten**
| Q             | A
| ------------- | ---
| Tickets       | #5093

### CODE REVIEW

**Comment by ilicmsreten** [comment]
`CI / Behat (PHP 7.4 lowest)` as I can see that one isn't related to this PR

**Comment by soyuka** [comment]
Patch looks nice. In my opinion this qualifies as a new feature as it was not supported in earlier versions. Wdyt ? In the case of a new feature you should target the `main` branch.

**Comment by ilicmsreten** [comment]
> Patch looks nice. In my opinion this qualifies as a new feature as it was not supported in earlier versions. Wdyt ? In the case of a new feature you should target the `main` branch.

I think this is more BUGFIX, because this PATCH was working in `v2.5` and when I wanted to update `core` to `v2.7` my tests were failing. 

The main reason is that `api-platform/core` didn't have a test to cover these cases.

I didn't have time to test this new `.features`  on the branch `v2.5` , will try to do it today or tomorrow, but if these features works on `v2.5` and not working without this fix on `v2.7` then for me this one is BUGFIX

**Comment by ilicmsreten** [comment]
@soyuka as I said, I tested on v2.5.4 that we use on our project and these `.features` tests are green

**Comment by ilicmsreten** [comment]
@soyuka what's the state of this one

**Pull request closed without merging**
