### PR TITLE
Fixed maxDepth handling for selfreferencing subresources

### PR DESCRIPTION
**Pull request by ghry5**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2533 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by ghry5** [comment]
@soyuka It seems php-cs-fixer is failing on some files I never touched... Since this is my first PR I would appreciate some help.

**Comment by soyuka** [comment]
The php-cs-fixer issue comes from the `2.3` branch don't worry!

**Comment by mRoca** [comment]
Hello, any news regarding this PR?

**Comment by flug** [comment]
@ghry5 Up is this pull request still valid?

**Comment by CoalaJoe** [comment]
Desperately waiting for this one to be pulled. 🙏

**Comment by soyuka** [comment]
rebased in https://github.com/api-platform/core/pull/3616

**Pull request closed without merging**
