### PR TITLE
Replace the old exception to status config with the new Symfony's YAML extension for PHP constants

### PR DESCRIPTION
**Pull request by meyerbaptiste**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by dunglas** [comment]
What do you think about not deprecating the previous way (I really don't like the `!php...` notation). We can still use it internally.

**Comment by teohhanhui** [comment]
The old way should be deprecated.

And the `!php/const` is YAML syntax (almost - pending symfony/symfony#22913). Users who don't like YAML syntax can already choose not to use YAML as the configuration file format.

**Comment by meyerbaptiste** [comment]
I'm agree with @teohhanhui, we should only support the most official way of doing it and not also a kind of "homemade hack".

**Comment by dunglas** [comment]
Let's do this so. Can you update the doc please @meyerbaptiste?

**Pull request merged**
