### PR TITLE
Remove sensio/framework-extra-bundle from the dev dependencies

### PR DESCRIPTION
**Pull request by meyerbaptiste**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

We forgot to remove `sensio/framework-extra-bundle` from the dev dependencies in #2108.

### CODE REVIEW

**Comment by meyerbaptiste** [comment]
Erf, we use converters in our custom controllers...

**Comment by teohhanhui** [comment]
Well, I say let's just keep the bundle. The intention was only to stop using the deprecated annoations, not to drop the bundle.

**Comment by meyerbaptiste** [comment]
Fixed...

**Comment by teohhanhui** [comment]
That's... pretty weird.

**Comment by meyerbaptiste** [comment]
Not really 🤔: https://github.com/symfony/http-kernel/blob/master/Controller/ArgumentResolver/RequestAttributeValueResolver.php

**Comment by soyuka** [comment]
phpstan issues?

**Comment by meyerbaptiste** [comment]
Not related @soyuka, they appeared with the last release of PHPStan (0.10.2).

**Comment by soyuka** [comment]
thanks @meyerbaptiste

**Pull request merged**
