### PR TITLE
EagerLoadingExtension: Disable partial fetching if entity has subclasses

### PR DESCRIPTION
**Pull request by desmax**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1069, #1071
| License       | MIT
| Doc PR        | none

Tried to fix this issue "Eager Loading Extension partial objects causing properties to not be available" #1069 So I basically select all fields for entities that have subclasses.

### CODE REVIEW

**Comment by dunglas** [comment]
Can you add a non-regression test?

**Comment by soyuka** [comment]
The perfect solution would be to call `joinRelations` on every `subclasses` instead of just doing this. 

The issue with this is that it won't eager load subclasses properties that might have a joined serialization group. Doctrine will then lazy-load them.

WDYT @desmax ?

**Comment by desmax** [comment]
@soyuka Looks like this is impossible. If you join with base class, doctrine would not allow to join relation of subclass: "Error: Class X has no association named Y".

**Comment by soyuka** [comment]
> Looks like this is impossible. 

Nothing is impossible.

But yes it might not be easy to do, and I don't know if it has a real gain. 

Can you add a test on this?

**Comment by desmax** [comment]
@soyuka I will try.
why am I getting this?
[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]
  `Behatch\Extension` extension file or class could not be located.
never worked with Behat before..

**Comment by soyuka** [comment]
@desmax do a rebase on `master`, we added php stan and a few errors were already fixed in #1074. IMO your solution is fine, just add a test and we'll merge ;)!

**Comment by Simperfit** [comment]
I agree with @soyuka and @dunglas a non-regression test should be added :)

@desmax Thank you for contributing to Api-Platform !

**Comment by desmax** [comment]
@soyuka I updated pull request. Added phpunit test, is it good enough?

**Comment by dunglas** [comment]
Thank you @desmax!

**Pull request merged**
