### PR TITLE
fix: use `getNestedConstraints()` instead of `getNestedContraints` wh…

### PR DESCRIPTION
**Pull request by soyuka**
…en available (#4564)

Signed-off-by: azjezz <azjezz@protonmail.com>

### CODE REVIEW

**Comment by norkunas** [comment]
Waiting for this to be released as it blocks to update Symfony to 5.4/6.0 :stuck_out_tongue:

**Comment by soyuka** [comment]
I know :) doing my best here ^^

**Comment by soyuka** [comment]
you should be able to use the 2.6 branch for now

**Comment by Raidri** [comment]
I don't get the fix. If I install a fresh api-platform with version 2.6.6 via composer, I just get the old version with the bug. What I have to do to get the fix? :)

**Comment by norkunas** [comment]
> I don't get the fix. If I install a fresh api-platform with version 2.6.6 via composer, I just get the old version with the bug. What I have to do to get the fix? :)

it's not released yet

**Pull request merged**
