### PR TITLE
fix resourceClassResolver when subclass is not declared

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ∅
| License       | MIT
| Doc PR        | ∅

I'm really not sure about this one.

I was trying for fun to add 100% coverage (sometimes it's useless, sometimes not) to this class when I noticed it wasn't really logic to go through the condition l53. I think it does not make sense testing the `$type` but maybe it does in an edge case that I didn't understood.

@dunglas maybe you can enlight me on this one?

### CODE REVIEW

**Comment by dunglas** [comment]
Looks good to me.

**Comment by soyuka** [comment]
ok I'm rebasing tomorrow

**Comment by dunglas** [comment]
Not sure it's required (there is no conflict). I would like to have the opinion of another reviewer.

**Comment by dunglas** [comment]
Thanks @soyuka

**Pull request merged**
