### PR TITLE
fix(elasticsearch): type error with $propertyName

### PR DESCRIPTION
**Pull request by GaryPEGEOT**
| Q             | A
| ------------- | ---
| Branch?       | 2.6
| Tickets       | 
| License       | MIT
| Doc PR        | N/A

Hi ! I have a `date` field in ElasticSearch, and I currently get the following error:

```json
{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "ApiPlatform\\Core\\Bridge\\Elasticsearch\\Serializer\\NameConverter\\InnerFieldsNameConverter::convertInnerFields(): Argument #1 ($propertyName) must be of type string, int given, called in vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverter.php on line 49",
  "trace": [...]
}
```

With an attribute typed as follow:

```php
class MyModel
{
    public ?DateTimeImmutable $updatedAt = null;
}
```
And the updatedAt is an ISO string.

Because there is no "propertyName" when using contructor.

### CODE REVIEW

**Comment by GaryPEGEOT** [comment]
Hi @dunglas ! Is it possible to provide PR for ElasticSearch integration, or is it on its way out?

**Comment by alanpoulain** [comment]
Based on the interface, `$propertyName` should always be a string.
I don't understand why it is an `int` in your case. Could you provide further explanation?

**Comment by GaryPEGEOT** [comment]
Hi ! It is supposed to be string when you're working with getter / setters, but when you're using contructor argument (in my case `DateTimeImmutable` constructor), property become function call argument index, in my case `0`, and with `strict-types` enabled, PHP is not happy with 0 passed a a string (which is normal)

**Comment by alanpoulain** [comment]
Could you show me where it happens in the Symfony serializer? I don't think it is normal, this parameter should always correspond to the property name. Maybe it's a bug in Symfony (or maybe you are using an old version of Symfony)?

**Comment by GaryPEGEOT** [comment]
Stack trace give me `ApiPlatform\\Core\\Bridge\\Elasticsearch\\Serializer\\NameConverter\\InnerFieldsNameConverter::convertInnerFields(): Argument #1 ($propertyName) must be of type string, int given, called in vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverter.php on line 49`

When using Xdebug, I can see that `$propertyName` is `0`, and `$class` is `DateTimeImmutable`, but it look normal to me, as it refers to constructor arguments of `DateTimeImmutable`, not to a property

**Comment by alanpoulain** [comment]
Could you give me the entire stack trace?

**Comment by GaryPEGEOT** [comment]
```
TypeError: ApiPlatform\Core\Bridge\Elasticsearch\Serializer\NameConverter\InnerFieldsNameConverter::convertInnerFields(): Argument #1 ($propertyName) must be of type string, int given, called in /vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverter.php on line 49
/vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverter.php:52
/vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverter.php:49
/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:353
/vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/ItemNormalizer.php:62
/vendor/symfony/serializer/Serializer.php:208
/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:508
/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:371
/vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/ItemNormalizer.php:62
/vendor/symfony/serializer/Serializer.php:208
/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:508
/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:371
/vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/ItemNormalizer.php:62
/vendor/symfony/serializer/Serializer.php:208
/vendor/api-platform/core/src/Bridge/Elasticsearch/DataProvider/Paginator.php:116
/vendor/api-platform/core/src/Hydra/Serializer/CollectionNormalizer.php:91
/vendor/api-platform/core/src/Hydra/Serializer/PartialCollectionViewNormalizer.php:55
/vendor/api-platform/core/src/Hydra/Serializer/CollectionFiltersNormalizer.php:73
/vendor/symfony/serializer/Serializer.php:154
/vendor/symfony/serializer/Serializer.php:127
/vendor/api-platform/core/src/EventListener/SerializeListener.php:95
/vendor/symfony/event-dispatcher/EventDispatcher.php:270
/vendor/symfony/event-dispatcher/EventDispatcher.php:230
/vendor/symfony/event-dispatcher/EventDispatcher.php:59
/vendor/symfony/http-kernel/HttpKernel.php:162
/vendor/symfony/http-kernel/HttpKernel.php:79
/vendor/symfony/http-kernel/Kernel.php:199
/vendor/symfony/http-kernel/HttpKernelBrowser.php:65
/vendor/symfony/framework-bundle/KernelBrowser.php:169
/vendor/symfony/browser-kit/AbstractBrowser.php:402
/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/Client.php:124
/tests/API/ProgramTest.php:58
```

**Comment by alanpoulain** [comment]
This is when you denormalize, what are you sending to the API?

**Comment by GaryPEGEOT** [comment]
It's the data from elastic search,  containing some date fields in a string ISO format, deserialized in a DTO like:
`class MyModel
{
    public ?DateTimeImmutable $updatedAt = null;
}`

**Pull request closed without merging**
