### PR TITLE
Fix private service deprecation in SearchFilterTest

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by soyuka** [comment]
> home/travis/build.sh: line 62:  3039 Segmentation fault      (core dumped) phpdbg -qrr vendor/bin/phpunit --coverage-php build/cov/coverage-phpunit.cov

We probably need @dunglas magic there

**Comment by dunglas** [comment]
Maybe Travis is (again) out of memory?

**Comment by dunglas** [comment]
Thanks @soyuka, I'll try to fix the segfault in another PR.

**Comment by teohhanhui** [comment]
Maybe we can try CircleCI.

**Comment by theofidry** [comment]
@dunglas it's PHP 7.1.2. I had segmentation faults in a few projects as well when using phpdbg as well, it's been fixed with PHP 7.1.3.

**Comment by soyuka** [comment]
> @dunglas it's PHP 7.1.2. I had segmentation faults in a few projects as well when using phpdbg as well, it's been fixed with PHP 7.1.3.
 

haha nice to know it isn't some dark dunglas-magic that made the tests pass :P

**Pull request merged**
