### PR TITLE
Add a new suggestion

### PR DESCRIPTION
**Pull request by Saphyel**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1199
| License       | MIT
| Doc PR        | none

To avoid people asking about CORS I think is better to suggest use it (or maybe should be part of the require?).

### CODE REVIEW

**Comment by dunglas** [comment]
NelmioCors is included in the distribution: https://github.com/api-platform/api-platform/blob/master/api/composer.json#L10

We use suggest to hint about optional features that can be enabled by installing extra packages. This is not the case here. I'm 👎 to add it.

**Comment by Saphyel** [comment]
@dunglas probably people that use symfony flex will end up wondering the same question (new people)... I just wanted to make it easier for them...

**Comment by dunglas** [comment]
I added an official Flex recipe for NelmioCord. Run `composer req cors` And you’re all set.
What we can maybe do instead is adding NelmioCors as a dependency of the `api-platform/api-pack`.

**Comment by krypton-code** [comment]
nelmio/cors-bundle should be included in the api-pack, absolutely!

**Pull request closed without merging**
