### PR TITLE
Page number int casting

### PR DESCRIPTION
**Pull request by IonBazan**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1860
| License       | MIT
| Doc PR        | no

This PR adds casting `page[page]` parameter to `int` and page number validation. It throws an error when page number is less than 1 and tries to convert a string to int when possible.

### CODE REVIEW

**Comment by meyerbaptiste** [comment]
Can you change the base branch? Bugfixes should target the `2.2` branch.

**Comment by teohhanhui** [comment]
Is it a problem with the rebase because I see some "totalCount" stuff which is not related to this bug?

**Comment by teohhanhui** [comment]
Something like this should do it:

```shell
git reset --hard upstream/2.2
git cherry-pick 25c831e
```

**Comment by soyuka** [comment]
thanks @IonBazan

**Pull request merged**
