### PR TITLE
Apply "static_lambda" CS rule under `src/` dir

### PR DESCRIPTION
**Pull request by phansys**
| Q             | A
| ------------- | ---
| Bug fix?      |no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by soyuka** [comment]
thoughts @api-platform/core-team ?

**Comment by alanpoulain** [comment]
I'm OK for this. Is there any CS rule to add it automatically?

**Review by vincentchalamon — APPROVED** [review]
I agree with @alanpoulain, it would be perfect with a php-cs rule

**Comment by phansys** [comment]
Sorry for the delay. If the rule is added, there are some cases where the replacement is invalid (I think in cases where the function is used for binding purposes).
I've followed that approach at first, but I had to leave the `tests/` directory out of this PR for that reason.

**Comment by soyuka** [comment]
Please rebase then :) and we'll fix this on 2.5

**Comment by soyuka** [comment]
Can you target 2.5 please ?

**Comment by phansys** [comment]
> Can you target 2.5 please ?

Done.

**Comment by soyuka** [comment]
Thanks @phansys !

**Pull request merged**
