### PR TITLE
chore(cs): Improve CS

### PR DESCRIPTION
**Pull request by webda2l**
| Q             | A
| ------------- | ---
| Branch?       | main for features / current stable version branch for bug fixes 
| Tickets       | #... 
| License       | MIT
| Doc PR        | api-platform/docs#... 

First commit is a must have IMO with some classes having really long line of _construct currently.
Second commit is more optional. I use @PhpCsFixer & @PhpCsFixer:risky fully personally but restricted some rule here to limit changes.

### CODE REVIEW

**Comment by alanpoulain** [comment]
Personally I like these changes!

**Comment by dunglas** [comment]
We should apply these changes on 2.7 or we have very bad time merging bug fixes in higher branches...

I like these changes too BUT I'm not sure they are worth the effort (doing the merge between 2.7 and 3.0 will be hard).

**Comment by alanpoulain** [comment]
I think doing it in 2.7 and merging it upstream would be hardest.
Maybe the best course of action would to do it just before the 3.1 release?

**Comment by dunglas** [comment]
That indeed looks like the best timing to do it. So we'll not have to care about 2.7 anymore.

**Comment by soyuka** [comment]
@webda2l API Platform 3.1 is around the corner, I've taken your changes at https://github.com/api-platform/core/pull/5330

**Pull request closed without merging**
