### PR TITLE
fix(doctrine): FilterEagerLoadingExtension breaks DQL if property name endings matches with query builder aliases

### PR DESCRIPTION
**Pull request by bsidev**
| Q             | A
| ------------- | ---
| Branch?       | 2.6
| Tickets       | #4591 
| License       | MIT
| Doc PR        | no

### CODE REVIEW

**Comment by soyuka** [comment]
Hi, thanks for the fix is this related to https://github.com/api-platform/core/pull/4577 ? as you added a test I'd like to merge this can you rebase? thanks!

**Comment by soyuka** [comment]
don't worry about phpstan I'll handle that later thanks!

**Comment by soyuka** [comment]
many thanks @bsidev !

**Comment by Ludo444** [comment]
any idea when this could get to bugfix release?

**Pull request merged**
