### PR TITLE
[RangeFilter] Cast float value to int if field is integer (to avoid 500)

### PR DESCRIPTION
**Pull request by karser**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2963
| License       | MIT

Hello, here is Solution 3 implemented as @soyuka [suggested](https://github.com/api-platform/core/issues/2963#issuecomment-517616913)

### CODE REVIEW

**Comment by teohhanhui** [comment]
I don't think this is the correct solution. It's better to just ignore the filter if the value is not in the correct type. (Or throw an exception leading to HTTP 400, if that makes sense.)

**Comment by karser** [comment]
@teohhanhui I performed upfront research and suggested [3 solutions](https://github.com/api-platform/core/issues/2963#issuecomment-517435386) in the original issue. You should have posted your thought there before it's implemented.

One core member recommends this approach and another discards it as soon as it is implemented. This is frustrating.

**Comment by teohhanhui** [comment]
@karser I understand your frustration, but not all of us are able to immediately respond to everything.

Thanks for your patience as we find the best solution together.

**Comment by soyuka** [comment]
We definitely need to reach a consensus... Your work here, even if we choose to log instead of convert can still be used and a few lines need to be changed. I won't see this as "unnecessary work" on the contrary it's a good step forward!

**Comment by karser** [comment]
Sure, let's discuss this once again.

>We should just ignore the filter if the value is not in the correct type (and log it, as we already do in some cases).

This is rare case and no one will notice that the float filter value is incorrect and silently ignored. And this bug will quickly be shipped to production. Logging will not help because no one reads logs unless sentry/graylog/etc is used.

If casting float to integer is not an option, I would rather throw a client error (400 code).
Although I still think that casting when possible is better than silently ignoring.

**Comment by dunglas** [comment]
Both ignoring and casting are fine to me. The sure thing is that a malformed query parameter must not allow to throw a 500 in production. Until we reach a consensus, I'm all in favor of merging this.

**Comment by soyuka** [comment]
> If casting float to integer is not an option, I would rather throw a client error (400 code).

throwing a 400 is too strong especially that it'd be triggerable through a query parameter :|.

> Although I still think that casting when possible is better than silently ignoring.

I do agree and I don't see the harm, if the documented type isn't respected the API should still work and it's the responsibility of the client to use the correct type when requesting it. Silently ignoring isn't an option and we would definitely log something.

**Comment by teohhanhui** [comment]
We already ignore invalid filters while logging the problem. If the user tries to filter, but it has no effect, they'll try to find out why. Silently rounding is more dangerous as it may lead to incorrect behaviour.

**Pull request closed without merging**
