### PR TITLE
Allow null attributes in ApiResource, ApiProperty and Operations

### PR DESCRIPTION
**Pull request by mtarld**
| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | #4411 
| License       | MIT

ApiProperty is already ok

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

**Comment by mtarld** [comment]
We need to handle as well 
- [ ] `ApiPlatform\Metadata\Operation`
- [ ] `ApiPlatform\Metadata\Get`
- [ ] `ApiPlatform\Metadata\Post`
- [ ] `ApiPlatform\Metadata\Put`
- [ ] `ApiPlatform\Metadata\Patch`
- [ ] `ApiPlatform\Metadata\Delete`
- [ ] `ApiPlatform\Metadata\GraphQl\Operation`
- [ ]  `ApiPlatform\Metadata\GraphQl\Query`
- [ ] `ApiPlatform\Metadata\GraphQl\QueryCollection`
- [ ] `ApiPlatform\Metadata\GraphQl\Mutation`
- [ ] `ApiPlatform\Metadata\GraphQl\Subscription`

**Review by azjezz — APPROVED** [review]

**Review by dunglas — CHANGES_REQUESTED** [review]
Actually, there is a design issue. The getters can return `null`, but it's not possible to pass `null` to the withers (as in https://github.com/api-platform/core/blob/main/src/Core/Metadata/Resource/ResourceMetadata.php).

`null` is a special value saying "this property hasn't been defined yet". Once it's define, it cannot be reset.

**Comment by dunglas** [comment]
Also, I think that all default values should be `null`, or it's almost useless to make them nullable.

**Comment by soyuka** [comment]
superseeded by https://github.com/api-platform/core/pull/4449 thanks @mtarld  !

**Pull request closed without merging**
