### PR TITLE
Drop dependency on fig/link-util

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Tickets       | -
| License       | MIT
| Doc PR        | -

To tidy up deps a bit since this is not needed.

### CODE REVIEW

**Review by dunglas — APPROVED** [review]
1 less dependency 🎉

Could you run PHP CS Fixer and amend the commit message (prefixing it with `chore: ` should make the linter happy) please?
Other issues don't look related.

**Comment by nicolas-grekas** [comment]
> prefixing it with chore: should make the linter happy

Sorry I don't get what this means :grimacing: 
The diff generated by the cs-fixer is wrong: the class *is* used in that file. Dunno what could cause this false positive.

**Comment by dunglas** [comment]
We are following the "conventional commits" spec to automatically generate changelogs. Commit messages have to be prefixed by the type of change. Here it's probably `chore: ` as it's not really a fix nor a new feature.

**Comment by nicolas-grekas** [comment]
prefix added to the commit message

**Comment by soyuka** [comment]
thanks @nicolas-grekas

**Pull request merged**
