### PR TITLE
HOTFIX Enable opportunity manage symfony route options.

### PR DESCRIPTION
**Pull request by fedotovaleksandr**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | api-platform/doc#1234

*Please update this template with something that matches your PR*
Sorry I don't know about Doc PR

### CODE REVIEW

**Comment by dunglas** [comment]
@fedotovaleksandr Good idea, but as the name can be configured with the `route_name` key, I suggest to rename the key `route_options`. WDYT?

**Comment by fedotovaleksandr** [comment]
I rename key, bro :+1:

**Comment by soyuka** [comment]
We need to document this as well or we will just forget that the feature exists :p.

**Comment by dunglas** [comment]
An alternative PR has now been merged. Closing.

**Pull request closed without merging**
