### PR TITLE
feat(graphql): partial pagination for page based pagination

### PR DESCRIPTION
**Pull request by xavierleune**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Tickets       | Closes api-platform/api-platform#2310 api-platform/api-platform#1996 #4764
| License       | MIT
| Doc PR        | todo

This pull requests fixes the paginator to offer a partial pagination for page based pagination, as already stated in the documentation. This part seems to have been forgotten during initial implementation, so I suggest to merge it in the branch 3.2.

### CODE REVIEW

**Comment by xavierleune** [comment]
@soyuka hi, what do you think of this PR?

**Comment by soyuka** [comment]
it introduces interfaces therefore we should merge that to `main` (3.3 should come out before end of February)

**Comment by xavierleune** [comment]
@soyuka ok ! I rebased my branch against main and fixed the tests

**Comment by soyuka** [comment]
thanks @xavierleune !

**Pull request merged**
