### PR TITLE
Merge 3.4

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Comment by soyuka** [comment]
@dwgebler  we've more tests on 4.0 and the patch actually breaks some of them (I was kinda expecting this), not sure what to do though the symfony patch will definitely work. @dunglas any idea on what should be done?

**Comment by dunglas** [comment]
Indeed this looks like the patch introduced a real bug. We should likely revert it and wait for https://github.com/symfony/symfony/pull/59047.

**Comment by dwgebler** [comment]
@soyuka has it broken any tests except this one?

```
--- Failed steps:

001 Scenario: Requesting a different format in the Accept header and in the URL should error                                                     # features/security/validate_response_types.feature:13
      And the JSON node "detail" should be equal to 'Requested format "text/xml" is not supported. Supported MIME types are "application/json".' # features/security/validate_response_types.feature:18
        The node 'detail' value is '"Requested format \"text\/xml\" is not supported. Supported MIME types are \"application\/json\", \"application\/problem+json\"."', 'Requested format "text/xml" is not supported. Supported MIME types are "application/json".' expected (Exception)
```

Because that seems like you can reasonably just adjust the expected output of the test. It hasn't changed the expected outcome of the scenario under test ("Requesting a different format in the Accept header and in the URL should error" - it still errors for the right reason), just the message it returns.

**Comment by soyuka** [comment]
What bothers me is that `problem+json` is no an actual supported type you can use as an `Accept` format.

**Comment by dwgebler** [comment]
> What bothers me is that `problem+json` is no an actual supported type you can use as an `Accept` format.

Well, @dunglas has reviewed the Symfony patch I submitted against 6.4 but who knows when that will make it into a release.

There are three options:

1. Revert the API Platform patch and accept it's broken with worker processes until a patched Symfony release is available. But I would count this as quite a severe bug, I'm honestly surprised no one else encountered it long before I did. There must be systems running in production today that could be, will be, have been impacted by this even if those organisations haven't noticed or found the cause.

2. Change the expected test outcome here and accept a temporary, much less severe bug that API Platform may, in limited circumstances, purport to support application/problem+json as a valid request format.

3. Dig deeper into API Platform and fix the way it generates and compares supported types more thoroughly. This seems a bit pointless and the wrong approach when the Symfony patch is coming.

It's not my product to say, it's yours to decide, but I would probably take option 2 if it was me just to provide users with a working fix that can be reverted when Symfony is patched in the hopefully near future. But as a member of Symfony, maybe Kevin is able to expedite the proper fix there, I don't know.

**Pull request merged**
