### PR TITLE
add php 7.3 to travis

### PR DESCRIPTION
**Pull request by andreybolonin**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by antograssiot** [comment]
This will need https://github.com/doctrine/doctrine2/pull/7325 to be released

**Comment by antograssiot** [comment]
https://github.com/doctrine/doctrine2/releases/tag/v2.6.3
Just restarted the Travis build

**Comment by teohhanhui** [comment]
SymfonyInsight failure is a false positive (YAML parsing error).

**Comment by teohhanhui** [comment]
Needs a rebase.

**Comment by antograssiot** [comment]
@andreybolonin would you mind rebasing and targeting 2.3 ?

**Comment by dunglas** [comment]
Thanks @andreybolonin, your commit has been included in #2403

**Pull request closed without merging**
