### PR TITLE
Disable the cache in development

### PR DESCRIPTION
**Pull request by Ener-Getick**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

It's a bit annoying to have to remove the cache each time you change something in development so I propose to remove or limit to the current process the cache.

### CODE REVIEW

**Comment by Ener-Getick** [comment]
This makes the tests a bit slower (+1,3s)
```console
guilhem@guilhem:~/github/cor$ phpunit
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

...............................................................  63 / 227 ( 27%)
............................................................... 126 / 227 ( 55%)
............................................................... 189 / 227 ( 83%)
......................................                          227 / 227 (100%)

Time: 6.27 seconds, Memory: 40.00MB

OK (227 tests, 1151 assertions)
guilhem@guilhem:~/github/cor$ phpunit
PHPUnit 5.4.6 by Sebastian Bergmann and contributors.

...............................................................  63 / 227 ( 27%)
............................................................... 126 / 227 ( 55%)
............................................................... 189 / 227 ( 83%)
......................................                          227 / 227 (100%)

Time: 7.62 seconds, Memory: 42.00MB

OK (227 tests, 1151 assertions)
```
but it is worth it imo.

**Comment by dunglas** [comment]
Thanks! 1 more second for the whole test suite doesn't matter and it's improve the DX.

**Comment by teohhanhui** [comment]
This is the wrong way to fix it. It makes DX much worse because the metadata system is unbearably slow without cache (when you have any non-trivial app). We need to at least use the in-memory (array) cache.

**Comment by teohhanhui** [comment]
Remember #468

**Comment by Ener-Getick** [comment]
@teohhanhui Can you try https://github.com/api-platform/core/pull/657 please ?

**Pull request merged**
