### PR TITLE
Remove wrong return doc

### PR DESCRIPTION
**Pull request by ddeboer**
| Q             | A
| ------------- | ---
| Branch?       | 2.6
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | no
| Tickets       | 
| License       | MIT
| Doc PR        |  

* The doc is superfluous, so rely on the return type instead.
* This fixes Psalm `InternalMethod` error when clients call methods 
  such as such as `toArray()` on `Response`, which is marked internal.

### CODE REVIEW

**Comment by alanpoulain** [comment]
Could you target `2.6` please?

**Review by dunglas — APPROVED** [review]
(When it will be rebased against 2.6)

**Comment by ddeboer** [comment]
Done!

**Comment by alanpoulain** [comment]
Thanks!

**Pull request merged**
