### PR TITLE
Do not restrict negotiation library to 2.3.1

### PR DESCRIPTION
**Pull request by soyuka**
ping @teohhanhui

### CODE REVIEW

**Comment by teohhanhui** [comment]
Needs rebase though... \o/

**Comment by dunglas** [comment]
I would just let `^2.0.3`, we'll not manually exclude all buggy patch versions of our deps.

**Comment by soyuka** [comment]
@dunglas agreed, so the patch was not needed :p. Rebased.

**Comment by teohhanhui** [comment]
@soyuka Still needs a rebase. :laughing:

**Comment by dunglas** [comment]
Thanks @soyuka.
@teohhanhui it's ok, I've just merged another PR in the meantime :)

**Pull request merged**
