### PR TITLE
[WIP] ReferenceType Configuration

### PR DESCRIPTION
**Pull request by Drachenkaetzchen**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | #350 |
| License | MIT |
| Doc PR | none yet |

This is a WIP PR for fixing #350. 

Right now, IRIs are relative, which means that it's impossible to tell from which host they come from. This PR attempts to fix that.

Tasks:
- [x] Reference Type can set in the configuration via the new configuration key `reference_type`. The supported values are `absolute_url`, `absolute_path`, `relative_path` and `network_path`, as supported by the [UrlGeneratorInterface](http://api.symfony.com/2.3/Symfony/Component/Routing/Generator/UrlGeneratorInterface.html)
- [x] The configuration key's default value is `absolute_path` to ensure BC
- [ ] `CollectionNormalizer` uses the `request_uri` as `@id`. This must be changed, but I'm not certain what's reasonable
- [ ] Documentation PR
- [ ] Unit Tests / Behat Tests. I'm not sure on how to test `absolute_url` and `network_path` as host names change of course, and I don't know how to do a Behat Test with a changing configuration

### CODE REVIEW

**Comment by theofidry** [comment]
@felicitus don't worry if the StyleCI fails, it cannot pass completely atm.

I'm not sure if this should be configuration, To me it would make more sense to have the FQCN for the reference type. But @dunglas is more qualified than me to answer this Hydra question.

**Comment by dunglas** [comment]
AFAIK relatives IRIs are perfect valid according to JSON-LD and Hydra spec. All available tools implementing these specs are able to deal with relative URLs. Using relative URLs has the advantage of reducing the size of the JSON document (performance, bandwidth...).
However, I've nothing against making this behavior configurable if we keep relative URLs as default.

**Comment by felicitus** [comment]
@dunglas yes, relative URIs should be default. However, in my scenario, I need to know the source of an entity, a relative URI was not enough in my case ;)

**Comment by dunglas** [comment]
Yes it would be nice to have the option and I'll be pleased to merge your marge when finished.

A workaround that works too is to change the JSON-LD document until retrieved and before saving it to transform relative URLs to absolute ones.

**Comment by sroze** [comment]
@felicitus any news about this PR?

**Comment by felicitus** [comment]
@sroze unfortunately no, I haven't had time to improve it yet.

**Comment by dunglas** [comment]
@felicitus any update regarding this PR? It would be nice to have.

**Comment by felicitus** [comment]
Unfortunately no, tbh I completely forgot about this. I will put it on my list :)

**Comment by Simperfit** [comment]
@felicitus Do you want some help on this ?

**Comment by felicitus** [comment]
@Simperfit sure, any help is appreciated :)

**Comment by Simperfit** [comment]
@felicitus Maybe you  should restart from the actual master and ill be glad to help you ;)

**Comment by felicitus** [comment]
@Simperfit if you have an idea regarding ` Unit Tests / Behat Tests. I'm not sure on how to test absolute_url and network_path as host names change of course, and I don't know how to do a Behat Test with a changing configuration` please let me know, that's the issue I'm having most trouble with

**Comment by Simperfit** [comment]
I was searching in this way too @felicitus but couldn't find anything about it. @sroze Do you have any idea how we can test that in behat ?

**Comment by maechler** [comment]
I just came across this issue. It looks quite similar to the pull request I just opened: https://github.com/api-platform/core/pull/751

I am not yet sure what would be the best way to add this feature..
Which way to go?

**Comment by Simperfit** [comment]
@maechler I thinks this is the right way to go

**Comment by Simperfit** [comment]
I think this should be restarted from exisint master, if you want to, feel free to ping me, i'll help ;).

**Pull request closed without merging**
