### PR TITLE
Rename getFilterValueFromUrl to getIdFromValue

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Rename private function SearchFilter::getFilterValueFromUrl to getIdFromValue

### CODE REVIEW

**Comment by teohhanhui** [comment]
Also, I doubt the return typehint (`string`) is correct.

**Comment by teohhanhui** [comment]
StyleCI issues unrelated.

**Comment by dunglas** [comment]
:+1:

**Comment by Simperfit** [comment]
LGTM

**Comment by dunglas** [comment]
The return string should indeed be mixed or scalar. Can you fix that too?

**Comment by teohhanhui** [comment]
@dunglas The StyleCI results are different for "push" vs "pr" checks above. Is that something you can fix?

**Comment by dunglas** [comment]
Can it be merged? I'll tweak the StyleCI config when I'll be back from vacation.

**Comment by teohhanhui** [comment]
Yes, it can be merged. Rebased.

**Comment by dunglas** [comment]
Thanks!

**Pull request merged**
