### PR TITLE
FilterEagerLoadingExtension accepts joins with class name as join value

### PR DESCRIPTION
**Pull request by partageit**
Hello,

The cause is explained in #2012.

I have two doubts/things i am not proud of:

- the optimisation is skipped for related joins
- i am not sure of the behaviour of this fix with composite relations.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2012 
| License       | MIT
| Doc PR        | None

### CODE REVIEW

**Comment by dunglas** [comment]
Shouldn't this patch target 2.2 as a bug fix?

**Comment by partageit** [comment]
@dunglas  You're right, the target is 2.2 :-s

How can i fix it ?
Should I create a new pull request ?

**Comment by dunglas** [comment]
You can change the target branch by editing your PR. Then you'll have to rebase against 2.2 (or create a new branch locally from 2.2, cherry-pick your commit, and push force in this remote branch).

**Comment by partageit** [comment]
Ok, i can't change the target PR, only the source branch...

You are now allowed to change the PR if you want.

If it does not work, i will create a new PR.

Sorry for the mistake :-s

**Pull request closed without merging**
