### PR TITLE
Fix nullable property on denormalization

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ∅
| License       | MIT
| Doc PR        | ∅

Bug introduced in https://github.com/api-platform/core/commit/e58bd7374fd01df3efa09e58dd58bf81db249ce3

### CODE REVIEW

**Comment by dunglas** [comment]
👍 (when the CI will be green). Good catch @soyuka

**Comment by soyuka** [comment]
How is it that appveyor takes ~3 min whereas travis takes ~20 min?

**Comment by dunglas** [comment]
Code coverage computation... But only one build is slow. The the other one take a few minutes.

**Comment by soyuka** [comment]
still 7 min for the lowest test (without coverage) on my PR vs ~3 min on app veyor, weird.

Dunno if scrutinizer is blocked right now.

**Comment by dunglas** [comment]
I just pushed a commit to optimize the build when running in non-coverage mode: https://github.com/api-platform/core/pull/697/commits/056a63f1bd696f14dcdee53fc9b5dd93417977e9

The Travis build also check Swagger compliance (it requires downloading some NPM packages), the AppVeyor build doesn't do that.

**Comment by dunglas** [comment]
Thanks you very much for discovering and fixing this bug @soyuka!

**Pull request merged**
