### PR TITLE
Allow unset PathItem method

### PR DESCRIPTION
**Pull request by d0niek**
After disabling itemOperation `GET`

```
    itemOperations: [
        'get' => [
            'controller' => ApiPlatform\Core\Action\NotFoundAction::class,
            'read' => false,
            'output' => false,
        ],
    ]
```

there is not nice way to remove that path from OpenApi docs. Now to do
that you have to write:

```
$pathItem = $openApi->getPaths()->getPath('/resource/{id}');
$openApi->getPaths()->addPath(
    '/resource/{id}',
    new Model\PathItem(
        $pathItem->getRef(),
        $pathItem->getSummary(),
        $pathItem->getDescription(),
        null,
        $pathItem->getPut(),
        $pathItem->getPost(),
        $pathItem->getDelete(),
        $pathItem->getOptions(),
        $pathItem->getHead(),
        $pathItem->getPatch(),
        $pathItem->getTrace(),
        $pathItem->getServers(),
        $pathItem->getParameters(),
    )
);
```

After change it will be:

```
$pathItem = $openApi->getPaths()->getPath('/resource/{id}');
$openApi->getPaths()->addPath(
    '/resource/{id}',
    $pathItem->withGet(null)
);
```

| Q             | A
| ------------- | ---
| Branch?       | main for features / current stable version branch for bug fixes 
| Bug fix?      | yes/no 
| New feature?  | yes/no 
| Deprecations? | yes/no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | api-platform/docs#...

### CODE REVIEW

**Review by alanpoulain — APPROVED** [review]
@soyuka could you check it too?

**Comment by soyuka** [comment]
can you target 2.6?

**Comment by d0niek** [comment]
> can you target 2.6?

Do you mean merge to branche 2.6 instead of main?

**Comment by soyuka** [comment]
yes please, and you will have to rebase then :)

**Comment by soyuka** [comment]
I don't want to mess your `main  branch, I picked your commit at https://github.com/api-platform/core/pull/4107

**Comment by d0niek** [comment]
@soyuka so I don't have to do new PR? 

I hope I helped you :-)

**Comment by soyuka** [comment]
Yes thanks for your patches I've added them :)

**Pull request closed without merging**
