### PR TITLE
Fix request auto-runner

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

This feature was broken since an update of SwaggerUI... Please be careful when updating Swagger UI.

### CODE REVIEW

**Comment by soyuka** [comment]
> Please be careful when updating Swagger UI.

Meaning? Who updated/merged it? How can we avoid this?

**Comment by meyerbaptiste** [comment]
> Who updated/merged it?

Me: https://github.com/api-platform/core/pull/1330 😃

**Comment by dunglas** [comment]
@soyuka I checked with Baptiste (it was him, not a big deal). We could introduce a functional test but it will require to add a WebDriver implementation... And our build will be still slower.

Instead, I think to propose to the Swagger UI team to add this feature upstream.

**Comment by dunglas** [comment]
During the meantime, the solution is to test manually when runing `./update-js.sh`

**Pull request merged**
