### PR TITLE
Remove a useless constructor

### PR DESCRIPTION
**Pull request by meyerbaptiste**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by teohhanhui** [comment]
You have to remove the unused imports too...

**Comment by meyerbaptiste** [comment]
Oops, I forgot to run PHP-CS-Fixer 🙄

**Comment by meyerbaptiste** [comment]
Coveralls makes me cry.

**Comment by dunglas** [comment]
Thanks @meyerbaptiste

**Pull request merged**
