### PR TITLE
Use getter/setter for relation

### PR DESCRIPTION
**Pull request by theofidry**
Linked to #217.

### CODE REVIEW

**Comment by dunglas** [comment]
It would be better to add a new test so we'll be sure that both public properties and get/setters work.

**Comment by theofidry** [comment]
Yeah, kind of made that to make sure it was related and that my issue was similar. I won't have the time to solve this week :/

**Comment by theofidry** [comment]
Btw this happens for adders/removers and setter with default value.

**Comment by theofidry** [comment]
Note to myself: check the `enabled` property thing

**Comment by theofidry** [comment]
@dunglas do you have any idea regarding this issue? I'm a bit stuck with it, not the right tool, not enough time and a bit lost to where to look at too. It seems pretty a pretty big issue to me.

**Comment by theofidry** [comment]
ping @dunglas

**Comment by dunglas** [comment]
I fixed it in https://github.com/dunglas/DunglasApiBundle/tree/v2-metadata
I just check for a method starting with set, not worrying about the number of required parameters.

**Comment by theofidry** [comment]
From what I remember here's the cases to consider:

* property is public
* property is accessible via a setter or/*and* adder (may happen for collections. Personally I never use both setter and adder for a collection, but it *may* happen and we have to consider this case, which one has the priority? Symfony property accessor prioritise the adder)
* property has only a getter (is not public but don't have any adder/setter)
* the adder/setter has optional values (the bug was that in those case, the default value was always chosen regardless of if we provided a value or not)

**Comment by theofidry** [comment]
Wait whut?! @dunglas I've found a strange case in v1.0. If I have only an adder like `::addJob()` for my property (collection) `$jobs`, it will never pass in it. However, if I add a function `::addJobs()` or `::setJob()`, the adder will be properly called... :sob:

**Pull request closed without merging**
