### PR TITLE
Add the header_comment rule to the PHP-CS-Fixer's configuration

### PR DESCRIPTION
**Pull request by meyerbaptiste**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by dunglas** [comment]
I wasn't aware of this option. Great!

**Comment by soyuka** [comment]
IIRC we removed this because it was causing issues with `declare(strict_types=1);`. Anyway +1 for adding it back if this works!

**Comment by dunglas** [comment]
The problem was with StyleCI.

**Comment by dunglas** [comment]
Thanks @meyerbaptiste

**Comment by soyuka** [comment]
> The problem was with StyleCI

Oh yes! Nice that we can add it through php-cs-fixer :) Thanks @meyerbaptiste !

**Comment by teohhanhui** [comment]
You mean this is fixed? https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2590

**Comment by meyerbaptiste** [comment]
Well I think `after_declare_strict` and `after_open` resolve this issue...

**Comment by soyuka** [comment]
Okay so this was definitely related to php-cs-fixer :p. Nice workaround @meyerbaptiste!

**Comment by teohhanhui** [comment]
Okay, I get it now. The way our CS is, we have never been affected by that bug. I just assumed we were... :sweat_smile:

**Pull request merged**
