### PR TITLE
Swagger: change the type of IDs in URL to string

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1177
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by backbone87** [comment]
While i think taht this fixes the problem wouldnt it be better to set the Parameters according to the API-Platform Metadata?

**Comment by soyuka** [comment]
+1 @backbone87 why is this hardcoded?

**Comment by dunglas** [comment]
By definition, a part of an URL is necessarily a string isn't it?

There are other cases where the current behavior is faulty (for insrance when using composite identifiers).
Why should we introduce a heavier logic if this tiny patch fixes all cases?

**Comment by backbone87** [comment]
for composite PKs i would rly like a spec like this:
```
"/books/{isbn}/chapters/{chapter_index}": {
  "get": {
    "parameters": [
      {
        "name": "isbn",
        "in": "path",
        "required": true,
        "type": "string"
      },
      {
        "name": "chapter_index",
        "in": "path",
        "required": true,
        "type": "integer"
      }
    ]
  }
}
```

but yes, just making it a string would allow anything allowed in URLs. but that doesnt provide nice inputs on GUIs that take Open API Specs as a base (like Swagger UI)

**Comment by dunglas** [comment]
The rationale behind this is related to how JSON-LD works. A JSON-LD document is identified by an URL (included in the `@id` property). There is no native concept of "composite keys" in a JSON-LD and in hypermedia APIs in general. There is a single identifier for a resource: its URL.

We imported this concept in API Platform, composite keys are basically just a hack to support this Doctrine feature (and its why it's in the data provider and not in the IRI converter). I think we shouldn't change that. Composite keys shouldn't escape from the Doctrine layer, outside key are just a single identifier.

> but yes, just making it a string would allow anything allowed in URLs. but that doesnt provide nice inputs on GUIs that take Open API Specs as a base (like Swagger UI)

Do you have an example? I don't understand how it can change something because an URL is by definition a string, to include a int in an URL, you must cast it to a string at some point.

**Comment by dunglas** [comment]
> but yes, just making it a string would allow anything allowed in URLs.

Yes, but the validation still occurs server-side. If you pute an invalid ID, you'll get a 404. Not a big deal to me.

**Comment by backbone87** [comment]
> The rationale behind this is related to how JSON-LD works. A JSON-LD document is identified by an URL (included in the @id property). There is no native concept of "composite keys" in a JSON-LD and in hypermedia APIs in general. There is a single identifier for a resource: its URL.

But the only interface that json-ld has in that sense is "give me the resource for IRI", which is the `IriConverter`. The interface of the `IriConverter` is good. i am talking how it works internally. And internally we do use the router to parse the IRI, but insteadof doin ALL the parsing in the router, there is a subparsing process within the `ItemDataProvider`, which violates SRP imho. An interface only sets requirements on the outside, not on a specific implementation and the concept of multiple identifier values of an entity is well known inside the default implementation of the `IriConverter` (note: i explicitly not use the RDB terminology here)

**Comment by backbone87** [comment]
> Yes, but the validation still occurs server-side. If you pute an invalid ID, you'll get a 404. Not a big deal to me.

That ensures integrety, but not best usability of client side tools using the Open API spec to build the UI.

**Comment by soyuka** [comment]
@dunglas in the UI there's client side validation according to types. It's therefore cleaner to have correct properties and types. Anyway, I'm 👍 on this patch because it fixes the blocking bug. Though I'd be 👍 if someone wanted to return the correct types. About composite identifiers I'm not sure that they could be supported as 2 fields in swagger (`string` would be fine).

**Comment by dunglas** [comment]
I agree with @soyuka proposal. @backbone87 I get your point and indeed documenting a precise type would be better from an UX point of view. If you want to create a patch to do a better type detection, I'll be happy to merge it!

**Comment by backbone87** [comment]
i am also perfectly fine with this PR being a quick fix. also tested it and it works

**Comment by backbone87** [comment]
this needs to be merged into master

**Comment by dunglas** [comment]
@backbone87 done

**Pull request merged**
