### PR TITLE
Fix serialization of nested non-resource objects

### PR DESCRIPTION
**Pull request by backbone87**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | ?
| Deprecations? | ?
| Tests pass?   | n/a
| Fixed tickets | #1222
| License       | MIT
| Doc PR        | n/a

possible fix for #1222, for discussions pls refer to that issue

### CODE REVIEW

**Comment by backbone87** [comment]
@soyuka i did a mistake, i forgot to pull your test case before rebasing with current master, do you have the tests still local?

**Comment by backbone87** [comment]
nvm, i could get the commit back with this neat trick: https://medium.com/git-tips/githubs-reflog-a9ff21ff765f

**Comment by backbone87** [comment]
when can we expect a merge on this?

**Comment by dunglas** [comment]
Thanks @backbone87 @soyuka

**Pull request merged**
