### PR TITLE
Update Behat dependencies to friends-of-behat for sf5 compat

### PR DESCRIPTION
**Pull request by thbil**
| Q             | A
| ------------- | ---
| Bug fix?      | yes 
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #... 
| License       | MIT
| Doc PR        | api-platform/docs#...

Replace `behat/mink` by `friends-of-behat/mink`, `behat/mink-browserkit-driver` by `friends-of-behat/mink-browserkit-driver`, and `behat/mink-extension` by `friends-of-behat/mink-extension` for sf5 compat (see https://github.com/Behat/MinkExtension/pull/360#issuecomment-631583136).

### CODE REVIEW

**Comment by alanpoulain** [comment]
It seems to break the tests.

**Comment by thbil** [comment]
> It seems to break the tests.

Indeed ! :) @soyuka told me he'll take a look to understand why.

**Comment by antograssiot** [comment]
There is work to do to integrate behatch when switching to these libraries. I did it in our app recently but it's quite some work depending on the number of existing Behat Context, anyway it is not as easy as replacing the libs from my experience.

**Comment by soyuka** [comment]
If anyone wants to give it a try don't hesitate. We should also update the symfony2-extension package.

**Comment by antograssiot** [comment]
On a first quick look, the error comes from those hacks

https://github.com/api-platform/core/blob/master/features/bootstrap/HttpHeaderContext.php#L35
https://github.com/api-platform/core/blob/master/features/bootstrap/HttpHeaderContext.php#L46

We can't see null anymore

**Comment by dunglas** [comment]
Replaced by #3792. Thanks @thbil, your contribution was very helpful!!

**Pull request closed without merging**
