### PR TITLE
Fix travis test

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

I've modified the test with the other commit this one is to fix the tests

### CODE REVIEW

**Comment by Simperfit** [comment]
ping @teohhanhui

**Comment by teohhanhui** [comment]
:+1:

**Comment by teohhanhui** [comment]
ping @api-platform/core-team

**Comment by vincentchalamon** [comment]
👍 
How this test could fail now, and didn't fail earlier?

**Comment by teohhanhui** [comment]
Travis works in mysterious ways :laughing:

@vincentchalamon I suppose you must have asked yourself that same question when you opened #513 :stuck_out_tongue:

**Comment by vincentchalamon** [comment]
@teohhanhui You're totally right ^^ I didn't understand why my original PR revel this bug… Travis seems strange sometimes, so does Scrutinizer…

**Comment by soyuka** [comment]
It's always the same test, context order isn't stable.

**Comment by dunglas** [comment]
👍 for @soyuka solution. I this one anyway to make Travis green again.

**Pull request merged**
