### PR TITLE
Fix build with Symfony 4.3

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by dunglas** [comment]
Shouldn't we merge #2784 in 2.4 instead?

**Comment by teohhanhui** [comment]
@dunglas But without the Symfony Messenger changes? As even for experimental code we should not do BC break in a patch version, only in minor version.

**Comment by teohhanhui** [comment]
Or are we able to keep BC on our end?

**Comment by dunglas** [comment]
The BC introduced by Symfony in Messenger is annoying, I'm not really sure of what to do.

**Comment by teohhanhui** [comment]
Maybe we could merge this first. It's harmless. If we decide to do more (e.g. deprecation fixes), we can do that later?

**Comment by dunglas** [comment]
I agree

**Pull request merged**
