### PR TITLE
Use dependencies compatible with Symfony 3

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by sroze** [comment]
I'm happy to upgrade the FOSUserBundle dependency to the 2.0 branch (ATM still in beta) as it's only dev dependencies and will probably be release as stable at some point :)

**Comment by dunglas** [comment]
It should be easy because I'ce already done the upgrade in the master branch, but I was wondering if it is a good idea for 1.1: it will force all users already having an app using both ApiBundle and FosUserBundle to upgrade to FosUserBundle 2 and it can be hard to do, especially for apps in maintenance mode.

What do you think about this alternative solution: skip tests related to FosUser when using Symfony 3?

**Comment by sroze** [comment]
That's a fair choice IMO. Then we simply have to add the following line in Travis:
```
if [ "$SYMFONY_VERSION" = "3.0.*" ]; then composer remove --dev --no-update friendsofsymfony/user-bundle; fi
```

**Comment by sroze** [comment]
It would be nice to support the both though. Then we can just add an OR in the dependency and based on the existing classes, we activate the different implementations. That way composer will automatically chose 1.x for Symfony < 3, and 2.x-dev for SF 3.

**Pull request closed without merging**
