### PR TITLE
specify left join for filter associations if there was a previous left join

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/api-platform/core/pull/789#issuecomment-302324794
| License       | MIT
| Doc PR        | n/a

see https://github.com/api-platform/core/pull/789#issuecomment-296218102

### CODE REVIEW

**Comment by soyuka** [comment]
@wadjeroudi may you test this patch to see if it fixes your issue? Thanks!

**Comment by wadjeroudi** [comment]
@soyuka man you're not a lazy guy for sure :+1: 
Will test this afternoon and tell you. Thank you !

**Comment by soyuka** [comment]
> you're not a lazy guy for sure

Wrong, a good developer should be lazy by definition :smile:

**Comment by wadjeroudi** [comment]
@soyuka it seems good for my use case. Thx.

**Pull request merged**
