### PR TITLE
Revert merge master into 2.2

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/api-platform/core/pull/1850#issuecomment-385812855
| License       | MIT
| Doc PR        | N/A

Please see #1923 for how it's done.

### CODE REVIEW

**Comment by teohhanhui** [comment]
159 files changed :scream: :sweat_smile:

**Comment by teohhanhui** [comment]
Travis build almost completed on my repo: https://travis-ci.org/teohhanhui/api-platform-core/builds/374012816

It should be fine. :smiley:

**Comment by soyuka** [comment]
Oh yeah :heart: thanks a lot @teohhanhui

**Comment by sroze** [comment]
❤️

**Comment by dunglas** [comment]
Thank you very much for handling this!!

**Comment by teohhanhui** [comment]
@soyuka suggested that I write a blog post about it. Maybe we could make it a post mortem analysis? And how we could prevent this from happening again... 😂

**Comment by dunglas** [comment]
would be great!

**Comment by sroze** [comment]
Definitely! It would be a nice one. Just the fact I've lost ~3 hours going to the wrong direction shows it definitely deserves a blog post (it would have saved me some time hehe)

**Pull request merged**
