### PR TITLE
Fix #510

### LINKED ISSUE #510: [2.x] Call non-existing object returns 500
When I call `GET /callers/42` (where 42 does not exist in database), it returns a 500 instead of a 404. This is due to serialization of a non-existing object.

I think the issue can be related to [`ItemDataProvider::getItem` method](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L92) which calls `EntityManager::getReference` method, but no validation is triggered to check if the related object exists (I guess `getReference` method only returns a reference of an object whatever it exists or not).

### PR DESCRIPTION
**Pull request by vincentchalamon**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #510
| License       | MIT

### CODE REVIEW

**Comment by dunglas** [comment]
👍 

Can you add a test to prevent future regressions?

**Comment by dunglas** [comment]
Thank you @vincentchalamon

**Comment by teohhanhui** [comment]
This is the same as #496

**Comment by dunglas** [comment]
Oops, sorry @teohhanhui I missed this one (I've not reviewed all pending PR yet).

**Pull request merged**
