### PR TITLE
feat (metadata): added PostCollection operation

### PR DESCRIPTION
**Pull request by joerndyherrn**
| Q             | A
| ------------- | ---
| Branch       | main
| License       | MIT

Implemented a new operation: PostCollection in order to be able to return multiple entities when having a custom POST controller

### CODE REVIEW

**Comment by joerndyherrn** [comment]
@soyuka Probably don't need to fix ResourceMetadataCollection as of https://github.com/api-platform/core/pull/5520/files#r1160520085
But won't get a green pipe though - would you mind to check another failed test: https://github.com/api-platform/core/actions/runs/4805382502/jobs/8551742674?pr=5570

**Comment by soyuka** [comment]
It looks weird to me to have a POST that returns a Collection but why not! 
 @dunglas any thoughts?

**Comment by mrossard** [comment]
Isn't this just supposed to be a POST on a custom resource that represents a collection of another type of resource? 
You'd return a single resource, but it would contain a collection of something else, which is pretty simple to do and closer to what a POST should be doing as far as i can see.

**Comment by joerndyherrn** [comment]
@mrossard No, let me explain it with a simple example:
We got a dictionary where we‘d like to add multiple words to it. As response we want a collection of those persisted entities.

**Comment by mrossard** [comment]
> @mrossard No, let me explain it with a simple example: We got a dictionary where we‘d like to add multiple words to it. As response we want a collection of those persisted entities.

Well as far as i know, that's not actually supposed to be done in one single request. What i described earlier was the "best" way I know of doing that while staying close to standards - if you create a specific resource that represents a "group of words", you can POST a "group of words" and get a single "group of words" in return.
That being said it's not great either since it means you're creating subresources on the fly...but batch operations are just not really supported by the standards (or maybe i'm just ignorant in that regard?).

**Pull request closed without merging**
