### PR TITLE
fix(metadata) Added phpdoc to ORM

### PR DESCRIPTION
**Pull request by stephanvierkant**
| Q             | A
| ------------- | ---
| Branch?       |3.3
| Tickets       | n/a
| License       | MIT
| Doc PR        | n/a

I've added some more phpdoc annotations. Please let me know if I should add more. I've added just some annotations that are relevant for me own use cases.

### CODE REVIEW

**Comment by soyuka** [comment]
sure but don't forget to run cs-fixer, phpstan and to respect the commit lint rules, thanks.

**Comment by stephanvierkant** [comment]
I'll do! That's why I made it a draft PR, because I didn't run it yet.

**Comment by stephanvierkant** [comment]
@soyuka PHPStan doesn't recognize 'Foo' as a `class-string`. 

I can ignore the error (as false positive), add a `/** @var class-string /*` to it, or use something like 'Foo\Bar' as a test string. What do you want me to do?

**Comment by stephanvierkant** [comment]
Because 'Foo' wasn't recognized as a `class-string`, I've used `Dummy::class` instead.

**Comment by soyuka** [comment]
nice thanks!

**Pull request merged**
