### PR TITLE
Require symfony/http-kernel 3.1

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Fix Composer dependencies. Builds were failing...

### CODE REVIEW

**Comment by teohhanhui** [comment]
ping @api-platform/core-team

**Comment by theofidry** [comment]
:+1: at the moment HTTP Foundation is hard dependency, even if I wish it wasn't the case

**Comment by teohhanhui** [comment]
@theofidry This is bumping HTTP Kernel, not HTTP Foundation.

**Comment by theofidry** [comment]
ha wait you are adding it to dev my bad. And kernel yeah: then why is it needed? They are both in dev as they are in required?

**Comment by teohhanhui** [comment]
The latest dev version of `symfony/framework-bundle` requires `symfony/http-kernel` ~3.1

**Comment by theofidry** [comment]
We have classes like [FormatRequestListener](https://github.com/api-platform/core/blob/master/src/EventListener/FormatRequestListener.php) which depends on it and are not considered to be part of the bridge. That makes it a required dependency, hence should be in the required no?

**Comment by teohhanhui** [comment]
Updated.

**Comment by sroze** [comment]
:+1:

**Pull request merged**
