### PR TITLE
Ensure PHPStan version stability

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by soyuka** [comment]
Would be cleaner to merge this in `2.0`, then merge `2.0` in `master` + only fix phpstan to avoid conflicts no?

WDYT?

**Comment by teohhanhui** [comment]
I don't think this would create conflicts, but I leave that up to whoever does the merge. :stuck_out_tongue:

**Comment by teohhanhui** [comment]
But sure, cleaner commit log lol...

**Comment by soyuka** [comment]
Hmm, the error is weird now :P.

**Comment by teohhanhui** [comment]
Yeah, it's weird. Could it have been caused by incorrect usage of PHPStan?

**Comment by teohhanhui** [comment]
Maybe @ondrejmirtes could help us figure this out. :laughing:

**Comment by meyerbaptiste** [comment]
The problem comes from this PR https://github.com/phpstan/phpstan/pull/255#issuecomment-317240387 and the `Symfony\Component\DependencyInjection\ExpressionLanguage` class which extends a non-existent class.

But why does PHPStan analyze this class? We have no reference to this one in our codebase for this branch.

**Comment by ondrejmirtes** [comment]
I'll look into, I'm sure there's some reason PHPStan tries to load this class.

**Comment by meyerbaptiste** [comment]
You're right @ondrejmirtes. PHPStan tries to load this class when it creates the type map of the `Symfony\Component\DependencyInjection\ContainerBuilder` class (we have many references to this one) which has an `$expressionLanguage` attribute (`ExpressionLangage|null`).

But errors at this level should not be displayed, right?

**Comment by ondrejmirtes** [comment]
Current behaviour is actually an improvement because in 0.7, the PHPStan process would crash on a fatal error. I'll evaluate this situation and get back to you.

**Comment by ondrejmirtes** [comment]
You can always put this in `ignoreErrors` :)

**Comment by mvrhov** [comment]
Do you need global require? PHPStan is now available as a phar.

**Comment by soyuka** [comment]
Thanks @teohhanhui

**Pull request merged**
