### PR TITLE
Fix indentation in Travis CI config

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

@dunglas Can we introduce an `.editorconfig` file, so that we may rid ourselves of problems like this going forward?

### CODE REVIEW

**Comment by Simperfit** [comment]
👍

**Comment by soyuka** [comment]
> Can we introduce an .editorconfig file, so that we may rid ourselves of problems like this going forward?

+1

**Comment by dunglas** [comment]
Thanks! +1 for the `.editorconfig` file.

**Comment by teohhanhui** [comment]
Followed up in #661

**Pull request merged**
