### PR TITLE
Allow changing the location of Swagger UI

### PR DESCRIPTION
**Pull request by antograssiot**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/api-platform/api-platform/issues/935
| License       | MIT
| Doc PR        | 

This PR re-enable [what's described in the doc](https://api-platform.com/docs/core/swagger/#changing-the-location-of-swagger-ui)

### CODE REVIEW

**Comment by teohhanhui** [comment]
I don't think this is the right way to fix it.

**Comment by teohhanhui** [comment]
We should provide a way to customize the path instead.

**Comment by teohhanhui** [comment]
I don't find any route that uses `SwaggerUiAction`, so it's actually enabled by `SwaggerUiListener`, right?

**Comment by teohhanhui** [comment]
I imagine we could add a configuration such as:

```yaml
api_platform:
    openapi:
        swagger_ui:
            enabled: true
            path: /docs
```

and deprecate `enable_swagger_ui`.

**Comment by antograssiot** [comment]
Indeed the listener  is handling it by forcing the controller of `api_entrypoint`. I too think it can be improved but wanted first to restore the old/documented behavior

**Comment by teohhanhui** [comment]
Note to self: This problem was not properly considered in the [JWT docs](https://github.com/api-platform/docs/blob/2.4/core/jwt.md).

**Comment by kl3sk** [comment]
I'll just test this branch as explain on https://github.com/api-platform/core/issues/2753 and confirm that work for me

**Comment by marcoreni** [comment]
Is this still broken? It should at least be specified inside the docs...

**Comment by soyuka** [comment]
@teohhanhui is something preventing us to merge this?

**Comment by antograssiot** [comment]
updated, rebased and targeting 2.5 now

**Comment by soyuka** [comment]
merged in https://github.com/api-platform/core/pull/3241 thanks @antograssiot

**Pull request closed without merging**
