### PR TITLE
Fix CS & PHPDoc

### PR DESCRIPTION
**Pull request by meyerbaptiste**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by dunglas** [comment]
Thanks @meyerbaptiste

**Comment by teohhanhui** [comment]
We should run php-cs-fixer in Travis build :smile:

**Comment by soyuka** [comment]
And add some git commit hook for everyone to use :tada: (I always forget to run it)

**Comment by dunglas** [comment]
StyleCI runs php-cs-fixer. It isn't able to catch that AFAIK, it's a PHPStorm analysis here.

**Comment by meyerbaptiste** [comment]
2 fixes comes from php-cs-fixer here, but they are not caught by StyleCI.

**Comment by soyuka** [comment]
What global version of php-cs-fixer are you using? Do you have options on top of the [.php_cs](https://github.com/api-platform/core/blob/master/.php_cs) file?

**Comment by meyerbaptiste** [comment]
I use php-cs-fixer 1.11 and the `.php_cs` file with no more options.
Fixes are:
* https://github.com/api-platform/core/pull/778/files#diff-86fab9484f0fd2fb39b7687ce79c68b7L106
* https://github.com/api-platform/core/pull/778/files#diff-8c2af436263d0764dd62c893d03bf301L20

**Comment by soyuka** [comment]
Weird, I'm using `1.12` and that's the diff I'm producing on master: https://gist.github.com/soyuka/38d0757f529805a737fb05aef0c4bc50. Someone knows why it removes every dot at the end of comments?

> PHP CS Fixer version 1.12.0 by Fabien Potencier and Dariusz Ruminski (ddac737)

**Comment by meyerbaptiste** [comment]
Explanations here:
* https://github.com/symfony/symfony/pull/19198
* https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2020

**Comment by soyuka** [comment]
Thanks! Searched but didn't find those. So, we should remove dots too?

**Pull request merged**
