### PR TITLE
Extracting table alias includes any SQL function names

### PR DESCRIPTION
**Pull request by botjaeger**
https://github.com/api-platform/api-platform/issues/2507

### CODE REVIEW

**Comment by soyuka** [comment]
I'd like a non-regression test this looks quite specific.

**Comment by botjaeger** [comment]
The solution doesn't work when the query is something like this

```
->addOrderBy("CASE
                 WHEN $alias.stage = 'NEW_APPLICATION' THEN 0
                 WHEN $alias.stage = 'ARCHIVED' THEN 1
                 WHEN $alias.stage = 'SEND_TO_CLIENT' THEN 2
                 WHEN $alias.stage = 'CLIENT_APPROVED' THEN 3
                 WHEN $alias.stage = 'SCREEN_CANDIDATE' THEN 4
                 WHEN $alias.stage = 'EXAM' THEN 5
                 WHEN $alias.stage = 'INTERVIEW' THEN 6
                 WHEN $alias.stage = 'SEND_OFFER' THEN 7
                 WHEN $alias.stage = 'SIGN_CONTRACT' THEN 8
             END", 'DESC');
```

this will result to 

`The alias \"CASE\n                 WHEN o\" does not exist in the QueryBuilder.`

but I can use the `FIELD` function

**Comment by botjaeger** [comment]
I updated the PR.

This is assuming that all doctrine alias is single character only

**Comment by mrossard** [comment]
> This is assuming that all doctrine alias is single character only

This doesn't seem realistic at all, for example if you use ApiPlatform\Doctrine\Orm\Util\QueryNameGenerator::generateJoinAlias() to get your aliases they won't be 1 character.

**Comment by botjaeger** [comment]
I agree. will close this

**Pull request closed without merging**
