### PR TITLE
feat: deactivate NelmioApiDocBundle by default

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #538 
| License       | MIT
| Doc PR        | update doc

### CODE REVIEW

**Comment by dunglas** [comment]
I'm -1 to drop the NelmioApiDoc bridge. It works, is stable and easy to maintain. A lot of work has been done on it. I prefer to keep it.

Does this composer trick work on Windows? When installing the lib as a dependency of another project?
What is the interest of doing this (the version is still hardcoded) instead of versioning the vendor?
If we take that path, the cleaner solution is to add a package.json file in the standard edition to retrieve the JS lib, but I prefer to have something working out of the box without requiring npm, node and so on. It is just a small dev dependency.

**Comment by Simperfit** [comment]
I'm +1 on dropping the bridge or make it disabled by default.

But I tested to remove and download it, but it will be too much work for windows too. I prefer to keep it inside too.

**Comment by dunglas** [comment]
The bridge is already disabled by default since https://github.com/api-platform/api-platform/pull/113 was merged.

**Comment by soyuka** [comment]
> I'm -1 to drop the NelmioApiDoc bridge. It works, is stable and easy to maintain. A lot of work has been done on it. I prefer to keep it.

+1

> It is just a small dev dependency.

But it is embed inside api-platform's source code?

**Comment by teohhanhui** [comment]
> The bridge is already disabled by default since api-platform/api-platform#113 was merged.

You mean the route is not there by default...

Anyway, if we have no interest in maintaining it anymore, we should just remove it altogether. My 2c...

**Comment by dunglas** [comment]
The Swagger UI integration is pretty recent and not as tested as the NelmioApiDoc integration. I propose to keep it but disabled by default and to deprecate it at the same time than NelmioApiDoc.

**Comment by soyuka** [comment]
I'd keep NelmioApiDoc too. Still, it bother's me a lot having swagger-ui sources inside api-platform's source code.

**Comment by dunglas** [comment]
It's just the dist. What we can do is to add a script to download automatically the last version when we do a `composer update` and check that we use the last version in the CI?

**Comment by soyuka** [comment]
That's the only way I see to get the latest tag:

```
git clone --depth 1 https://github.com/swagger-api/swagger-ui/
git fetch --tags
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
```

Won't it be best to let the user install swagger-ui instead if he wants to? Maybe you want it inside api-platform/api-platform but IMO it's not necessary in the core.

**Comment by dunglas** [comment]
+1 to have it in the standard edition but not in the core.

**Comment by dunglas** [comment]
Thank you @Simperfit

**Pull request merged**
