### PR TITLE
[Do not merge] Revert merge master into 2.2

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/api-platform/core/pull/1850#issuecomment-385812855
| License       | MIT
| Doc PR        | N/A

Relevant merged PRs (that should actually go into `2.2`) since #1850:
- [x] #1853 Fix the Behat test suite with low dependencies (@meyerbaptiste)
- [x] #1871 Page number int casting (@IonBazan)
- [x] #1876 Add missing doctrine alias removed in doctrine-bundle@1.9 (@soyuka)
- [x] #1861 fix exists filter (@IonBazan)
- [x] #1875 Enable item route on collection subresources (@soyuka)
- [ ] #1874 Forward operation name in the iri converter (@soyuka)
- [x] #1868 Allow GraphQL to filter on nested property (@antograssiot)
- [x] #1866 The OrderFilter is still triggering bad deprecation/function calls (@antograssiot)
- [x] Revert 3465b41 (@soyuka) (pushed to `2.2` branch without PR)
- [x] #1883 [GraphQL] Remove useless double check of access_control in resolvers (@alanpoulain)
- [x] #1888 Move coverage jobs to CircleCI (@teohhanhui)
- [x] #1892 add some local caches where they are missing (@bendavies)
- [ ] #1877 Allow subresource items in the iri converter (@soyuka)
- [x] #1894 fix normalizer cache key generation (@bendavies)
- [x] #1897 EagerLoadingExtension: respect fetchEager=false on an association (@bendavies)
- [x] #1905 Simplify boolean filter (@bendavies)
- [x] #1907 Revert "Simplify boolean filter" (@teohhanhui)
- [x] #1908 RFC: Cache trait (@bendavies)
- [x] #1886 [GraphQL] Fix introspection (graphql-php / GraphiQL) (@alanpoulain)

https://github.com/api-platform/core/compare/d34fba5...2.2
(start from after d611aa0 and 3fdd546 which was when #1850 was merged)

This is done with `git cherry-pick`, so it's not meant for merging. If everything looks good, I will use this to create a revert commit and open another PR.

Unfortunately for @soyuka, you'll probably have to resubmit your 2 PRs if they're appropriate for `2.2`.  (Unless they can be rebased here.) Do you think that's okay?

### CODE REVIEW

**Comment by sroze** [comment]
Seems better than my approach of `git revert -m 1 d611aa0991c90ca36d90318eff3f689eb3a98e5a` and then manually fixing the conflicts:
https://github.com/api-platform/core/compare/2.2...sroze:2.2-but-better?expand=1

**Comment by teohhanhui** [comment]
@sroze I told you so :stuck_out_tongue:

**Comment by sroze** [comment]
We had to try both ways 🤷‍♂️

**Comment by soyuka** [comment]
Nice work :heart: 

> Unfortunately for @soyuka, you'll probably have to resubmit your 2 PRs if they're appropriate for 2.2. (Unless they can be rebased here.) Do you think that's okay?

Which ones? Yeah it's okay I just need to make sure I have the work locally somewhere :P.

**Comment by teohhanhui** [comment]
@soyuka See the checklist above. And you can rebase them based on the old commits in this repo. We're not going to rebase. This is only how I come up with the manual revert commit. =P

**Comment by soyuka** [comment]
-  #1874 Forward operation name in the iri converter (@soyuka)
- #1877 Allow subresource items in the iri converter (@soyuka)

Are both fixes to the 2.2 branch. 

Only https://github.com/api-platform/core/pull/1899 should've been merged on master instead of 2.2.

**Comment by teohhanhui** [comment]
Travis is passing: https://travis-ci.org/teohhanhui/api-platform-core/builds/373994838

The merge conflicts here are to be ignored. :smile:

**Comment by sroze** [comment]
Closed in favor of #1924

**Pull request closed without merging**
