### PR TITLE
Refresh routes when an entity is created

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | a lot
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by soyuka** [comment]
I'm wondering, what does this fix? Why do we need this? Has this an impact on performances? I remember an issue on the subject but can't put my hand on it anymore :|

**Comment by dunglas** [comment]
When you download the distribution and and add an entity you got a 404 error if you don't clear the cache. I need to test if this patch fix this.

**Comment by soyuka** [comment]
Hmm, clearing the cache should be the developer's work no? I'm not sure that it's a good idea to do it on the fly.

**Comment by dunglas** [comment]
@soyuka we already do that (here and in Symfony) in dev mode for everything. It's definitely a bug to miss this specific case.

**Comment by dunglas** [comment]
I've just tried it on a real world project, and it works as expected.

**Pull request merged**
