### PR TITLE
Move coverage jobs to CircleCI

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

I propose to use CircleCI for the test coverage jobs. Also includes some minor CI / test-related fixes.

Todo:
- [x] Use GNU Parallel (only for PHPUnit tests, as Behat tests modify the database...)
- [ ] Investigate why ApiPlatformExtensionTest takes a very long time
- [x] Remove coverage jobs from Travis CI

### CODE REVIEW

**Comment by dunglas** [comment]
We can try, but it annoys me to have 3 different CI systems (AppVeyor, Travis and Circle), it means more maintenance.
Isn't it possible to switch entirely from Travis to Circle?

Also, Circle is not very used in the PHP community. It means a harder learning curve for contributors.

**Comment by teohhanhui** [comment]
You can see the builds of my fork on CircleCI here: https://circleci.com/gh/teohhanhui/workflows/api-platform-core/tree/ci%2Fparallel-jobs

**Comment by teohhanhui** [comment]
I agree with this article, we could split our builds on Travis CI and CircleCI to take full advantage of the free resources provided by both.

https://www.codementor.io/adiroiban/circle-ci-2-0-for-open-source-projects-hsi1rpufs

**Comment by dunglas** [comment]
I've added Circle CI to the org, can you push force?

**Comment by teohhanhui** [comment]
I have to note that the `upload-coverage` job only passed because I have the `COVERALLS_REPO_TOKEN` in the CircleCI project for my fork, and it indeed uploaded the coverage report for the forked repository.

So we'll need to disable the coveralls integration for pull requests unless we find a better way.

**Comment by teohhanhui** [comment]
We could switch to codecov:

> Repo tokens are not required for public repos tested on Travis-Org, CircleCI or AppVeyor.

**Comment by dunglas** [comment]
Ok for me, but please also keep coveralls for the main branches so we don't loose the history.

**Comment by teohhanhui** [comment]
What do you think about also using CircleCI for lint jobs? It should simplify our Travis CI config further... And it'll likely allow the Travis CI build to complete faster as there is one less job in the queue.

**Comment by dunglas** [comment]
Good idea!

**Comment by teohhanhui** [comment]
But I think we should not expand the scope of this PR further before we verify that things work as expected. Lol...

**Comment by teohhanhui** [comment]
This should be good to merge. :smiley:

**Comment by soyuka** [comment]
cool stuff thansk @teohhanhui

**Comment by bendavies** [comment]
you can still easily parallelize behat. you just have to 

1. create N databases upfront.
2. export a token for the current parallel slot `parallel -j10 'export TEST_TOKEN={%}; vendor/bin/behat ... {}`
3. Register a doctrine connection factory which reads the value of `TEST_TOKEN` and connects to the correct database.

**Comment by teohhanhui** [comment]
@bendavies:
> create N databases upfront.

:scream: :scream_cat:

It's fast enough as it is. So I think it's okay for now? :stuck_out_tongue_winking_eye:

**Comment by bendavies** [comment]
yep, just saying it's possible :)

**Pull request merged**
