### PR TITLE
fix: Change order of mapping paths being loaded

### PR DESCRIPTION
**Pull request by tgrochowski**
| Q             | A
| ------------- | ---
| Branch?       | current stable version branch
| Tickets       | #4464 
| License       | MIT

Description of purpose for this PR is written in following issue.

https://github.com/api-platform/core/issues/4464

### CODE REVIEW

**Comment by alanpoulain** [comment]
Hello and thanks for your PR.
However it's a duplicate of https://github.com/api-platform/core/pull/3987.
It seems this change is really needed for Sylius, but it's a BC break.
@dunglas @soyuka WDYT? Should we merge it for 2.7 anyway?

**Comment by tgrochowski** [comment]
Thanks for fast reply and sorry for making a duplicate. I was just searching for similar issues, not PR's

**Comment by soyuka** [comment]
We can merge this for 2.7 I think and it needs a line in the changelog

**Comment by alanpoulain** [comment]
Thanks!

**Pull request merged**
