### PR TITLE
[GraphQL] Fix iterable type

### PR DESCRIPTION
**Pull request by alanpoulain**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/api-platform/api-platform/issues/704
| License       | MIT
| Doc PR        |

Fix the iterable type after a BC in graphql-php.
Maybe we need to force users to require a specific version of graphql-php in order to avoid this kind of issue.
For example in the doc, instead of:
`composer require webonyx/graphql-php`
we would have:
`composer require webonyx/graphql-php:^0.12.0`
WDYT?

### CODE REVIEW

**Comment by alanpoulain** [comment]
Errors seem not related.

**Comment by dunglas** [comment]
About the documentation, it will be a pain to update... But maybe should we change the version constraint in `require-dev` to `<1.0` to catch those errors when new versions are tagged?

**Comment by dunglas** [comment]
Can you rebase? Test should be green now.

**Comment by dunglas** [comment]
done @alanpoulain

**Comment by alanpoulain** [comment]
Rebase done.

**Comment by soyuka** [comment]
still failing for low version IMO you should constraint to `>0.12.0<1.0.0` (not sure of the format)

**Comment by dunglas** [comment]
Thanks @alanpoulain!

**Pull request merged**
