### PR TITLE
Eager Loading Extension does not use dynamic serialization context

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1039
| License       | MIT
| Doc PR        | na

ping @bwegrzyn may you try my branch to see if this fixes the issue? 
Could you please also give me an example of your dynamic context so that I can add a proper test for this use case?

Tyvm!

### CODE REVIEW

**Comment by bwegrzyn** [comment]
@soyuka Thanks, it looks like this will fix the issue. I will test it tonight and let you know.

My context builder looks for a "expand" parameter in the request (/users?expand=role). Based on the values in the expand parameter, it will verify and dynamically add groups to the context so that the serializer serializes those properties. In this case, the User resource has a Role resource (User->role). The serializer would not serialize the Role resource unless the serializer context contains the "role" group.

**Comment by bwegrzyn** [comment]
@soyuka Just tested your PR, it works as expected. Thanks!

**Comment by bwegrzyn** [comment]
I am curious about the requirements for it to use the groups from the ContextBuilder. 

Why do you require isMethodSafe() or for it to be DELETE? DELETE doesn't return any content anyways, and isMethodSafe() prevents eager loading during POST/PUT requests.

**Comment by soyuka** [comment]
@bwegrzyn I need to refactor, indeed those are unneeded bits! I wanted to see if it actually fixed your issue before going further :).

**Comment by soyuka** [comment]
@bwegrzyn May you share your ContextBuilder (or an extract)? Thanks!

**Comment by bwegrzyn** [comment]
@soyuka This is what I'm using right now. WIP so far, but it seems to work fairly well despite certain short comings.

Maybe api-platform should support such a feature out of the box? It would be nice to support nested resource expansions using dot notation, but that may be something that the serializer component would need to support first.

```php
use ApiPlatform\Core\Serializer\SerializerContextBuilderInterface;
use Symfony\Component\HttpFoundation\Request;

class ContextBuilder implements SerializerContextBuilderInterface
{

    /**
     * @var SerializerContextBuilderInterface
     */
    private $decorated;

    public function __construct(SerializerContextBuilderInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function createFromRequest(Request $request, bool $normalization, array $extractedAttributes = null) : array
    {
        $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);

        // Only allow expansions on normalization
        if (!$normalization) {
            return $context;
        }

        $permittedExpansions = $context['permitted_expansions'] ?? [];

        $requestedExpansions = (array) $request->query->get('@expand', []);

        // Support CSV format for single parameter
        if (count($requestedExpansions) === 1) {
            $requestedExpansions = explode(',', $requestedExpansions[0]);
        }

        foreach ($requestedExpansions as $expansion) {
            $expansion = trim($expansion);
            if (in_array($expansion, $permittedExpansions)) {
                if (!isset($context['groups'])) {
                    $context['groups'] = [];
                }

                $context['groups'][] = $expansion;
            }
        }

        return $context;
    }

}
```

**Comment by dunglas** [comment]
Thank you very much @soyuka

**Pull request merged**
