### PR TITLE
Fix update-composer in CircleCI configuration

### PR DESCRIPTION
**Pull request by alanpoulain**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by teohhanhui** [comment]
`sudo`, in a Docker container? I'm not sure what's going on here...

**Comment by teohhanhui** [comment]
Maybe we should use our own Docker images for the CircleCI build, so that we could have more control and avoid weird issues like this in the future...

**Comment by teohhanhui** [comment]
Thanks @alanpoulain! :1st_place_medal:

**Comment by er1z** [comment]
@teohhanhui — `sudo` on composer update has to be used if its binary is outside current user scope. May be a workaround of installing under home dir + altering `PATH` could be a solution.

**Pull request merged**
