### PR TITLE
Unskip tests using Prophecy

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by soyuka** [comment]
Weird appveyor bug when installing deps:

> phpDocumentor\Reflection\DocBlock\Tags\BaseTag cannot implement phpDocumentor\Reflection\DocBlock\Tag - it is not an interface in C:\projects\dunglas\api-bundle\vendor\phpdocumentor\reflection-docblock\src\DocBlock\Tags\BaseTag.php on line 21

**Comment by dunglas** [comment]
@soyuka because it still use the built-in phpunit (which isn't up to date) instead of the one installed by Composer. I'll fix that.

**Comment by teohhanhui** [comment]
We must add `phpunit/phpunit` to `require-dev`. Currently it's only a coincidence that this works (transitive dependency through `php-mock/php-mock-phpunit`).

**Comment by dunglas** [comment]
@teohhanhui you're right, and we must remove it when a new release of the PHPUnit phar will be released.

**Comment by teohhanhui** [comment]
@dunglas The PHPUnit phar is already at 5.4.2

What am I missing?

**Comment by dunglas** [comment]
The PHPUnit PHAR doesn't include Prophecy 1.6.1 yet (and previous versions are buggy with Symfony 3.1).

**Comment by teohhanhui** [comment]
Requested here: https://github.com/sebastianbergmann/phpunit/issues/2201#issuecomment-224540306

**Pull request merged**
