### PR TITLE
Fix 3770

### PR DESCRIPTION
**Pull request by TheCrealm**
| Q             | A
| ------------- | ---
| Bug fix?      | no 
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Original PR       | #3770 
| License       | MIT
| Doc PR        | none

This PR implements the @Ignore annotation. Original PR: #3370

### CODE REVIEW

**Comment by TheCrealm** [comment]
By fixing this, i discovered that the @ignore annotation was introduced with symfony 5.1.
Because of that, this will always fail for php7.1 unit tests as php7.2 is the minimum php version for this.

(*Happy first pr noises*)

**Comment by soyuka** [comment]
May you add a unit test?

**Comment by TheCrealm** [comment]
Is this ok? @soyuka 
i looked at the other tests to figure out how to do it. At the end its covered :)

**Review by soyuka — APPROVED** [review]
Good work, thanks for taking this over!

**Comment by lucasgranberg** [comment]
We are discussing reverting this change at https://github.com/api-platform/api-platform/issues/1566 because this doesn't apply to schema generation so it would be better to do this with property metadata using `$propertyMetadata->withWritable(false)->withReadable(false)->isInitializable(false);`.
Adding a flag like `isIgnored` to the propertyMetadata could even be preferable to make all other extractors quit early.

What do people involved with this change think of that? The other option would be to do this separately for schema generation.

**Pull request merged**
