### PR TITLE
feat: refactor documentations

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Fix some scrutinizer issued

### CODE REVIEW

**Comment by dunglas** [comment]
Looks good to me, but I'll do a better review when I'll have acess to a computer.
Thanks for refactoring this @Simperfit!

**Comment by dunglas** [comment]
Can you rebase please?

**Comment by Simperfit** [comment]
@dunglas This PR has been rebased

**Comment by dunglas** [comment]
Thanks!

**Pull request merged**
