### PR TITLE
[Swagger] Do not tag a sub-resource operation with child resource

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

---

Before:

image

After:

image

### CODE REVIEW

**Comment by dunglas** [comment]
Can you give more insight? Wouldn't it be more logicial to only tag the example with `Answer` (as it's what it returns`?

**Comment by lyrixx** [comment]
Actually, I opened this PR to get some feedback. I'm really not sure about this one ;)

But for me it seems more logical to gather all root "resources" together as displayed on the screenshot.

What do you think?

**Comment by dunglas** [comment]
I don't know what to think about this one. Both behaviors looks "logical" to me... Any feedback @api-platform/core-team?

**Comment by soyuka** [comment]
It all comes down to https://github.com/api-platform/core/pull/1617#discussion_r158963911 (same problematic). To me both are valid:

1. On the subresource "initiator" (ex Question because route starts with Question)
2. On the class we retrieve (ex Answer, because we receive an Answer)

I'd even search for it in `Answer` in the first place because it returns a collection of `Answer` not a `Question`.

**Comment by Toflar** [comment]
This looks way more logical to me as well 👍  Listing the same thing twice only confuses first-time API users who will go like "wait, I read this already".

**Comment by meyerbaptiste** [comment]
IMO, `/api/questions/{id}/answer` should only be tagged with the `Answer` tag. Indeed, I want to deal with an `Answer` resource so I go to the `Answer` section.

**Comment by soyuka** [comment]
> IMO, /api/questions/{id}/answer should only be tagged with the Answer tag. Indeed, I want to deal with an Answer resource so I go to the Answer section.

Okay for swagger. Though, were should be the subresource configuration (see https://github.com/api-platform/api-platform/issues/529). To me it'd be easier to have it on the "Initiator" class.

**Comment by Simperfit** [comment]
@lyrixx could you please update this according to the discussion ?

**Comment by lyrixx** [comment]
Sure, But I don't know when. I should dedicate some time to work on API-Platform ;)

**Comment by Simperfit** [comment]
@lyrixx when you can :p

**Comment by soyuka** [comment]
Closing in favor of https://github.com/api-platform/core/issues/2706

**Review by Wyze5280 — COMMENTED** [review]
...

**Pull request closed without merging**
