### PR TITLE
[GraphQL] Fix collection field mutation

### PR DESCRIPTION
**Pull request by alanpoulain**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2093
| License       | MIT
| Doc PR        |

Fix collection fields not returned when a mutation is done.

### CODE REVIEW

**Comment by alanpoulain** [comment]
Tests are failing because of unrelated deprecations (Doctrine).

**Comment by Siregacvek** [comment]
Thanks for your PR. I tested it and there is still one issue. From GraphQL perspective the returned value is of `update` operation type, not `query`. So for example the security subsystem (e.g. voter) can deny this operation and dont allow return collection.

**Comment by alanpoulain** [comment]
@Siregacvek I don't understand. What you explain is the expected behavior, doesn't it? You are not doing a query but a mutation. So it's logical to have the operation type as a mutation.

**Comment by Siregacvek** [comment]
@alanpoulain , let me explain. Lets we have a mutation
```
mutation{
 updateEntity(input:{
    id:"entities/1"
    field:"new value"
    clientMutationId: ""
  }){
    id
    field
      relatedEntities{
      edges{
        node{
          id
        }
      }
    }
  }
}
```
I see here 2 requests (`update` and `query`) and I expect the following behavior:
1. I do update mutation on Entity, changing the property `field`. It's an `update` operation for sure.
2. Then I want to return the updated entity with some collection of related entities. Here I expect query-type request, because mutation already processed, I just want to return the current (new) state of entity with its related collection of other entities. Right now for the backend this step looks like an update operation on related collection. But it's not.
 
Am I not right?

**Comment by alanpoulain** [comment]
It doesn't seem logical to me. Returning the state of the entity is part of the mutation process.
This way, you can control how you want the normalization of a mutation and it can differ from the query one (see https://api-platform.com/docs/core/graphql#serialization-groups).
Moreover, it's coherent with the REST part of API Platform: https://api-platform.com/docs/core/serialization#using-different-serialization-groups-per-operation. When you're doing a `PUT`, you can control how you want the normalized data in the `put` operation type, not in the `get` one.

**Comment by Siregacvek** [comment]
@alanpoulain ok, I got you - it's other point of view on a process. Thanks for you work!

**Comment by alanpoulain** [comment]
Could we merge this PR?

**Comment by soyuka** [comment]
thanks @alanpoulain

**Pull request merged**
