### PR TITLE
feat:add test to sereliazer

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by dunglas** [comment]
:+1:

**Comment by Simperfit** [comment]
Rebased with master

**Comment by dunglas** [comment]
Thanks @Simperfit

**Comment by teohhanhui** [comment]
@Simperfit spelling: "serializer" :stuck_out_tongue:

**Pull request merged**
