### PR TITLE
fix(graphql): use depth for nested resource class operation

### PR DESCRIPTION
**Pull request by NicoHaase**
| Q             | A
| ------------- | ---
| Branch?       | 3.0
| Tickets       | #5310
| License       | MIT
| Doc PR        | api-platform/docs#... 

Reproducer for the bug reported in #5310

### CODE REVIEW

**Comment by alanpoulain** [comment]
Hello, thanks for this PR!
Could you use a dedicated resource though?

**Comment by NicoHaase** [comment]
> Hello, thanks for this PR! Could you use a dedicated resource though?

Sorry - this still needs some work, as I'm currently not able to reproduce the problem in an isolated test fase

**Comment by NicoHaase** [comment]
Let's see whether the CI triggers the same problem I could reproduce locally now. Also, I've found how my previous version of this reproducer differs from this one: by reordering the list of graphqloperations on the TreeDummy, I was able to fix the bug. Having QueryCollection first and then Query, no bug is thrown. This also resolves the problem in my own application.

But that looks pretty strange to me. Why should the order of these operations influence how a field is resolved?

**Comment by alanpoulain** [comment]
Hello @NicoHaase, I've made the fix I think is appropriate. What do you think of it?
@develth, does it fix your issue too?

**Comment by develth** [comment]
> Hello @NicoHaase, I've made the fix I think is appropriate. What do you think of it? @develth, does it fix your issue too?

will create a diff patch & test it - thx!

**Comment by develth** [comment]
Your fix was successful for me @alanpoulain !

**Review by soyuka — APPROVED** [review]

**Comment by NicoHaase** [comment]
I haven't checked this fix yet, but when the test is no longer failing, I would assume it works :) But what makes me curious is why ordering the operations makes a difference. This is not addressed in this fix

**Comment by alanpoulain** [comment]
It doesn't make a difference anymore since the nested operation will now always be selected depending on the type (collection or not).
Before it was not the case and the first operation on the resource was used.

**Pull request merged**
