### PR TITLE
fix(jsonld): allow @id, @context and @type on denormalization

### PR DESCRIPTION
**Pull request by soyuka**
#6225

### CODE REVIEW

**Comment by soyuka** [comment]
Hi, the best way to test the branch is to use https://getcomposer.org/doc/05-repositories.md#vcs with the fork and the branch

**Comment by ili101** [comment]
So as I said above https://github.com/api-platform/core/pull/6402#issuecomment-2142494980 this seems not to have any effect.
I don't quite understand Symfony's point of `isAllowedAttribute()` if it's being superseded by `getAllowedAttributes()`.
But this approach I made before works https://github.com/api-platform/core/pull/6274/. So using the same approach but instead of adding a new context option I just did what you did and added the items. branch: https://github.com/ili101/api-platform-core/tree/id (https://github.com/ili101/api-platform-core/commit/7f483074a757a395e378ff5ef8cf963b6e5a5ec1)

And with this it's possible to use the `@id` as [described in the documentation ](https://api-platform.com/docs/core/serialization/#denormalization) while using `allow_extra_attributes: false`

**Comment by soyuka** [comment]
nice, can you open a new PR to replace mine?

**Comment by soyuka** [comment]
superseeded by https://github.com/api-platform/core/pull/6451

**Pull request closed without merging**
