### PR TITLE
Fix ExistsFilter for inverse side of OneToOne association

### PR DESCRIPTION
**Pull request by sryabov**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Fixed tickets | #2049
| License       | MIT

### CODE REVIEW

**Comment by soyuka** [comment]
May you add a test to prevent regression? Thanks!

**Comment by sryabov** [comment]
I make something wrong with branch and don't know how to revert it =(

**Comment by teohhanhui** [comment]
@sryabov I can handle that if you want.

**Comment by teohhanhui** [comment]
@sryabov Reverted the incorrect merge.

**Comment by sryabov** [comment]
@teohhanhui it seems to be fixed, thx =)

**Comment by sryabov** [comment]
Phew, I made it =) All test are passed. Sorry for many commits, but local behat is not working correct:

```
Feature: Default values of HTTP cache headers
  In order to make API responses cacheable
  As an API software developer
  I need to be able to set default cache headers values

  @createSchema @dropSchema
  Scenario: Cache headers default value                                                   # features/http_cache/headers.feature:8
    When I send a "GET" request to "/relation_embedders"                                  # Behatch\Context\RestContext::iSendARequestTo()
    Then the response status code should be 200                                           # Behat\MinkExtension\Context\MinkContext::assertResponseStatus()
    And the header "Etag" should be equal to '"21248afbca1f242fd3009ac7cdf13293"'         # Behatch\Context\RestContext::theHeaderShouldBeEqualTo()
    And the header "Cache-Control" should be equal to "max-age=60, public, s-maxage=3600" # Behatch\Context\RestContext::theHeaderShouldBeEqualTo()
      The header 'Cache-Control' should be equal to 'max-age=60, public, s-maxage=3600', but it is: 'max-age=0, must-revalidate, private, s-maxage=3600'
      
      +--[ HTTP/1.1 200 | http://example.com/relation_embedders | KernelDriver ]
      |
      |  {"@context":"\/contexts\/RelationEmbedder","@id":"\/relation_embedders","@type":"hydra:Collection","hydra:member":[],"hydra:totalItems":0}
      |
    And the header "Vary" should be equal to "Accept, Cookie"                             # Behatch\Context\RestContext::theHeaderShouldBeEqualTo()
```

And one more thing: I think that you need to split Dummy fixture for normilize tests and for relations (include filters) tests.

**Comment by dunglas** [comment]
Thanks @sryabov!

**Pull request merged**
