### PR TITLE
add missing MetadataAwareNameConverterPass registration 🐛

### PR DESCRIPTION
**Pull request by bendavies**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2523
| License       | MIT
| Doc PR        | 

the `MetadataAwareNameConverter` wasn't being registered because the compiler pass had forgotten to be added :)

### CODE REVIEW

**Comment by antograssiot** [comment]
@bendavies I've updated the base branch to 2.4

**Comment by bendavies** [comment]
Thanks. I mean to do that

**Comment by antograssiot** [comment]
nice catch :+1:  

The failling tests on ES are related though and likely due to 
https://github.com/api-platform/core/blob/e2a7194b0f80320fc82c302859f7e51a7db23a42/src/Bridge/Elasticsearch/DataProvider/Filter/AbstractSearchFilter.php#L75
ping @meyerbaptiste

**Comment by soyuka** [comment]
It's because we changed the name converter. It works if we use the `CamelCaseToSnakeCaseNameConverter`  inside the `InnerFieldsNameConverter`, now it has the `MetadataAwareNameConverter`. I'm really not sure what we should do here.

**Comment by meyerbaptiste** [comment]
I just added a fix. Can you review my commit @soyuka?

**Comment by bendavies** [comment]
`MetadataAwareNameConverterPassTest` needs updating now

**Comment by soyuka** [comment]
LGTM, thanks @meyerbaptiste !

**Comment by meyerbaptiste** [comment]
Tests updated.

**Comment by bendavies** [comment]
looks good?

**Comment by soyuka** [comment]
thanks @meyerbaptiste @bendavies !

**Pull request merged**
