### PR TITLE
[GraphQL] Fix introspection (graphql-php / GraphiQL)

### PR DESCRIPTION
**Pull request by alanpoulain**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1880
| License       | MIT
| Doc PR        |

The best way to fix current issues with GraphQL introspection is to remove the problematic code.

We should be waiting for this PR to be merged https://github.com/facebook/graphql/pull/395 and changes to be affected to graphql-php and graphql-js in order to add it again.

The main lost feature is the ability to manage embedded entities.

A way to get this feature back will be to have two fields (one for an IRI, the other for the data) for relations but there is some work to be done.

### CODE REVIEW

**Comment by alanpoulain** [comment]
This is done.

**Comment by Simperfit** [comment]
Thanks @alanpoulain.

**Comment by BernardA** [comment]
@alanpoulain, please inform current status concerning embedded mutations. I have a bid entity which embeds a message entity, which embeds an attachment entity. As it is now, it seems that I need to create 3 create mutations. Is that still the case? Thanks.

**Comment by alanpoulain** [comment]
Yes it is: https://github.com/api-platform/core/issues/3258#issuecomment-553971707.

**Pull request merged**
