### PR TITLE
Remove unused trait import

### PR DESCRIPTION
**Pull request by norkunas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by soyuka** [comment]
Thanks @norkunas !

**Comment by teohhanhui** [comment]
Hmm... Was php-cs-fixer and phpstan not able to catch this?

**Comment by norkunas** [comment]
> Hmm... Were php-cs-fixer and phpstan not able to catch this?

PHPStan:
                                                                                                                        
 [ERROR] Found 5828 errors

**Comment by teohhanhui** [comment]
Yes, you need `mongodb` extension to run phpstan.

**Pull request merged**
