### PR TITLE
Allow to set maximum items per page at operation/resource level

### PR DESCRIPTION
**Pull request by norkunas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1587
| License       | MIT
| Doc PR        | none

### CODE REVIEW

**Comment by soyuka** [comment]
may you add a test?

**Comment by norkunas** [comment]
Test added.

**Comment by dunglas** [comment]
Thanks @norkunas!
Please add this to the documentation or this will definitely be forgotten: https://github.com/api-platform/docs/blob/master/core/pagination.md

**Comment by norkunas** [comment]
Will do.

**Pull request merged**
