### PR TITLE
Skip colors on travis job

### PR DESCRIPTION
**Pull request by soyuka**
They disabled logs when nb_lines > 10000, which is our case, this helps
debugging

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes \o/
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | na
| License       | MIT
| Doc PR        | na

### CODE REVIEW

**Comment by dunglas** [comment]
Thanks @soyuka

**Comment by teohhanhui** [comment]
Probably a better fix would be to reduce the verbosity of some of the installation logs. Colours are good...

**Comment by soyuka** [comment]
Behat alone is >10k lines no?

**Comment by teohhanhui** [comment]
Okay, now I'm not sure I get what this PR is supposed to do... \o/

**Comment by soyuka** [comment]
I don't remember what PR it was but the author was asking for help debugging. I had to fork his branch to execute the tests on my device because travis output was unreadable because colors where stripped. Can't find the reference, but travis clearly stated that above 10 000 lines, colors won't be outputted and we'll instead get ASCII characters.

**Comment by teohhanhui** [comment]
I think Travis stops showing log output when it hits 10000 lines (it's still available in the raw log). The way mozilla/fxa-content-server#488 handled it (reducing verbosity where unneeded) seems better to me.

**Comment by teohhanhui** [comment]
See https://twitter.com/travisci/status/174904509754118144 and travis-ci/docs-travis-ci-com#281

**Comment by soyuka** [comment]
Damn, I need to get my hand on the screenshot again. Anyway, if you really want colors back we can revert this ^^ but it's not a priority imo.

**Comment by teohhanhui** [comment]
Symfony uses colors too... :stuck_out_tongue:

https://github.com/symfony/symfony/blob/59f3f34cc84e93e287e0971d05bfe0edee8e20e2/.travis.yml

**Comment by soyuka** [comment]
> No colours = hard to read.

Many unix users would actually tell you that it is more a distraction 😛 . Thing is, it's way more readable than when colors are ASCII outputed no?

**Pull request merged**
