### PR TITLE
Remove duplicate code in DateFilter

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Missed in #529

### CODE REVIEW

**Comment by teohhanhui** [comment]
Duplicate code removed but coverage decreased...

jackie-chan-whut

**Comment by Simperfit** [comment]
@teohhanhui coverage is from 
space

**Comment by soyuka** [comment]
And -0.008% is a lot... Just merge the damn thing \o/

**Comment by Simperfit** [comment]
@soyuka It's red, do we merge red builds :p ?

**Comment by dunglas** [comment]
Thanks @teohhanhui

**Pull request merged**
