### PR TITLE
Reorder normalizers (tiny perf improvement)

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by teohhanhui** [comment]
Does this mean a perf improvement for GraphQL at the expense of JSON API? Not that I disagree with it. :laughing:

**Comment by teohhanhui** [comment]
Oops. The build failed on CircleCI because we haven't merged 2.2 back into master.

**Comment by dunglas** [comment]
Yes, but only if you enable both.

We advertise mainly JSONLD and GraphQL, IMO they must be the ones privilegied.

With the new improvements in Synfony, the improvement will be less significant (because the number of calls to supportsNormalization will be reduced a lot).

**Comment by teohhanhui** [comment]
Needs a rebase.

**Comment by soyuka** [comment]
#2524

**Pull request closed without merging**
