### PR TITLE
fix(JsonSchema): fix reDoc json sample values

### PR DESCRIPTION
**Pull request by ERuban**
| Q             | A
| ------------- | ---
| Branch?       | 3.1
| Tickets       | -
| License       | MIT

Reworking of https://github.com/api-platform/core/pull/5638 PR

### CODE REVIEW

**Comment by ERuban** [comment]
@soyuka hi, but `https://example.com` looks strange for iri also. It should be smth like `/books/{id}` in example

**Comment by ERuban** [comment]
👋

**Comment by soyuka** [comment]
still not good, either put `https://example.com/` or fix that in SwaggerUI... Best would be to even generate the proper IRI in our examples but this is not what the PR is doing.

**Comment by ERuban** [comment]
@soyuka ok, done

**Comment by soyuka** [comment]
thanks, to go further we'll see to implement #6058

**Pull request merged**
