### PR TITLE
fix(schema): generation with default operation

### PR DESCRIPTION
**Pull request by vincentchalamon**
| Q             | A
| ------------- | ---
| Branch?       | 2.7
| Tickets       | https://github.com/api-platform/core/issues/4613#issuecomment-1174770854
| License       | MIT

### CODE REVIEW

**Comment by dannyvw** [comment]
@vincentchalamon This is also fixed https://github.com/api-platform/core/issues/4613#issuecomment-1175197212

**Comment by vincentchalamon** [comment]
@dannyvw Awesome! Thanks for testing!
Just fixing the CI, then I think it'll be good for merge.

**Comment by soyuka** [comment]
Thanks @vincentchalamon !

**Comment by jamesisaac** [comment]
Great fix, thanks.  Resolved a similar problem I was having.

**Pull request merged**
