### PR TITLE
Upgrade the Negotiation library

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

See willdurand/Negotiation#94

TODO:

- [x] Wait for a new tag

### CODE REVIEW

**Comment by insekticid** [comment]
create new tag ASAP, because after composer update you get willdurand/negotiation v 2.3 and after that will work only first output normalizer with same format (e.g. json)

```
api_platform:
    formats:
        jsonld:  ['application/ld+json']
        jsonhal: ['application/hal+json']
```

request:
`
curl -X GET --header 'Accept: application/hal+json' 
`
response is in 'ld+json' format (the first one in config)

**Comment by soyuka** [comment]
We're aware of that @insekticid this is why the version should have been patched in #1102! See the root cause [here](https://github.com/willdurand/Negotiation/pull/92#issuecomment-299248503). We're waiting for [this](https://github.com/willdurand/Negotiation/issues/94) to be merged to fix the issue :).

**Comment by insekticid** [comment]
I understand, but you should add warning to Api Platform website, or create new tag with '"willdurand/negotiation": "^2.0.3 <2.3",' since this will be fixed

**Comment by meyerbaptiste** [comment]
The new tag is here, this PR can be updated!

**Comment by soyuka** [comment]
Hmm we have the same phpstan errors then in #1113

**Comment by soyuka** [comment]
@dunglas could you set up a new tag (also in api-platform/api-platform)? Thanks!

**Comment by dunglas** [comment]
@soyuka why?

**Comment by soyuka** [comment]
Composer should take the last available version of the negotation library? If that's the case, never mind ;).

**Comment by dunglas** [comment]
@soyuka yep. And when doing `composer install`,  it will take an older one.

**Comment by teohhanhui** [comment]
@dunglas Bumping the required version of `willdurand/negotation` is a BC break. :disappointed:

I believe it should be:

```json
"willdurand/negotiation": "^2.0.3 <2.3 || ^2.3.1",
```

**Comment by dunglas** [comment]
I haven't seen this PR was merged. There is no need to do that as a new version of a new version of 
`willdurand/negotiation` has been released. I've opened this PR just to run the test suite with the patched version.
I need to revert this PR.

**Comment by soyuka** [comment]
Yeah sorry my bad, thought it was needed. I've reverted it in #1115

**Pull request merged**
