### PR TITLE
Fix CS

### PR DESCRIPTION
**Pull request by meyerbaptiste**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Fix CS with the latest version of php-cs-fixer.

### CODE REVIEW

**Comment by meyerbaptiste** [comment]
To continue the initial discussion (https://github.com/api-platform/core/pull/778#issuecomment-250749389), I'm not sure about the good way. These changes break the tests. So, should we follow the Symfony CS, fix CS and tests or should we blacklist `phpdoc_annotation_without_dot` fixer in the php-cs-fixer configuration?

What are your opinions?

**Comment by dunglas** [comment]
I'm for fixing the tests and keeping our CS in sync with Symfony.

**Comment by dunglas** [comment]
Thanks @meyerbaptiste

**Comment by teohhanhui** [comment]
@dunglas So I suppose we need to fix this in schema-generator as well?

**Comment by dunglas** [comment]
@teohhanhui yes!

**Pull request merged**
