### PR TITLE
Ensure correct return type from AbstractItemNormalizer::normalizeRelation

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

Stricter type checking in `normalizeRelation` to improve code quality. Also cleaned up some ~dead~ wrong(?) code (related to #2073 and #2074).

### CODE REVIEW

**Comment by teohhanhui** [comment]
Pushed to wrong remote. Oops! :see_no_evil:

**Comment by teohhanhui** [comment]
Which part do you think is unsafe?

**Comment by teohhanhui** [comment]
I closed the previous PR because I try to take a safer approach here.

**Comment by soyuka** [comment]
Could you rebase @teohhanhui I want to merge this today

**Comment by teohhanhui** [comment]
Rebased.

**Pull request merged**
