### PR TITLE
Bump CI to check Symfony 5.1 compatibility

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

~Failures with Symfony 5.1 / `master` seem to be caused by a Symfony (`PropertyInfo`?) bug? (Bad detection of hasser method - a hasser method must never have any required arguments.)~ Fixed by #3410

Other Behat job failures caused by https://github.com/sebastianbergmann/phpcov/issues/94

### CODE REVIEW

**Comment by teohhanhui** [comment]
https://github.com/api-platform/core/pull/3386/checks?check_run_id=472800924#step:15:14

Should we set `LEGACY=0` for the `symfony-next` jobs? Since we only support `nelmio/api-doc-bundle` 2.x - is their 2.x branch still maintained?

**Comment by teohhanhui** [comment]
Currently, there is no UI indication for when the step has failed when using `continue-on-error: true`.

See https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/m-p/40599

**Comment by teohhanhui** [comment]
All CI jobs should be green again! :green_heart: :evergreen_tree:

**Comment by dunglas** [comment]
Thanks @teohhanhui 🎆

**Pull request merged**
