### PR TITLE
Update typo in interface

### PR DESCRIPTION
**Pull request by sroze**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | ø
| License       | MIT

So IDEs are happy with the `@see` and we can Ctrl+Click :)

### CODE REVIEW

**Comment by dunglas** [comment]
Can you target the 2.1 branch as it's a bug fix?

**Comment by sroze** [comment]
Not sure what I've just done while trying @stof's option of `git rebase --onto` 🤔

**Comment by sroze** [comment]
For the records, here what I've done...
```
git checkout update-typo-in-interface
git rebase --onto 2.1
git push origin +update-typo-in-interface
```

**Comment by sroze** [comment]
Well... this PR should work: #1502

**Comment by stof** [comment]
@sroze your should have used `git rebase --onto 2.1 master` as second command (to rebase all commits being in your branch and not in master onto 2.1). If you don't specify the beginning of the rebase, it defaults to the upstream of your branch (so `origin/update-typo-in-interface` in this case). But you had 0 commits belonging to your branch and not to `origin/update-typo-in-interface` (as your branch was pushed already).

**Pull request closed without merging**
