### PR TITLE
Update PaginationExtension.php

### PR DESCRIPTION
**Pull request by remoteclient**
This PR should allow to instantiate `DoctrineOrmPaginator` with a query instead of queryBuilder which allows to set hints. Hints are needed to make translations with gedmo/translatable work.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1694 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by remoteclient** [comment]
To get the right translations of properties of an entity you have to use hints described in the [documentation](http://atlantic18.github.io/DoctrineExtensions/doc/translatable.html#orm-query-hint) of gedmo/translatable.
To get items automatically retrieved from the database according to the requested locale, one could use a custom extension:
```php
<?php

namespace MWS\NutritionCalculatorBundle\Doctrine;


use ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\QueryItemExtensionInterface;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Gedmo\Translatable\TranslatableListener;
use MWS\NutritionCalculatorBundle\Entity\DogBreed;
use Symfony\Component\HttpFoundation\RequestStack;

final class DogBreedExtension implements QueryItemExtensionInterface
{
    private $entityManager;
    /**
     * @var RequestStack
     */
    private $requestStack;

    /**
     * DogBreedExtension constructor.
     * @param EntityManagerInterface $entityManager
     * @param RequestStack $requestStack
     */
    public function __construct(EntityManagerInterface $entityManager, RequestStack $requestStack)
    {
        $this->entityManager = $entityManager;
        $this->requestStack = $requestStack;
    }

    /**
     * @param QueryBuilder $queryBuilder
     * @param QueryNameGeneratorInterface $queryNameGenerator
     * @param string $resourceClass
     * @param array $identifiers
     * @param string|null $operationName
     * @param array $context
     */
    public function applyToItem(QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, array $identifiers, string $operationName = null, array $context = [])
    {
        $this->addHints($queryBuilder, $resourceClass);
    }

    /**
     *
     * @param QueryBuilder $queryBuilder
     * @param string       $resourceClass
     */
    private function addHints(QueryBuilder $queryBuilder, string $resourceClass)
    {
        if (DogBreed::class === $resourceClass) {

            $queryBuilder = $queryBuilder->getQuery();
            $queryBuilder->setHint(
                Query::HINT_CUSTOM_OUTPUT_WALKER,
                'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
            );
            // locale
            $queryBuilder->setHint(
                TranslatableListener::HINT_TRANSLATABLE_LOCALE,
                $this->requestStack->getCurrentRequest()->getLocale() // take locale from session or request etc.
            );
            // fallback
            $queryBuilder->setHint(
                TranslatableListener::HINT_FALLBACK,
                0 // fallback to default values in case if record is not translated
            );
            $queryBuilder->setHint(TranslatableListener::HINT_INNER_JOIN, true);

            $queryBuilder->getResult();
        }
    }
}
```
For collections this will only work with a custom collection data provider where you can play with the injected extensions. There you can call getResult() on the PaginationExtension and return a Paginator instance with the full query. But getResult() is only accepting the queryBuilder as Argument and hints can't be applied on a queryBuilder and so the hints will never make it into the query. Maybe my implementation of the collectionDataProvider make things clear:
```php
<?php
declare(strict_types=1);

namespace MWS\NutritionCalculatorBundle\DataProvider;

use ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\QueryCollectionExtensionInterface;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\QueryResultCollectionExtensionInterface;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGenerator;
use ApiPlatform\Core\DataProvider\CollectionDataProviderInterface;
use ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface;
use ApiPlatform\Core\Exception\ResourceClassNotSupportedException;
use ApiPlatform\Core\Exception\RuntimeException;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\Query;
use Gedmo\Translatable\TranslatableListener;
use MWS\NutritionCalculatorBundle\Entity\DogBreed;
use Symfony\Component\HttpFoundation\RequestStack;

class DogBreedCollectionDataProvider implements CollectionDataProviderInterface, RestrictedDataProviderInterface
{
    private $managerRegistry;
    private $collectionExtensions;
    private $requestStack;

    /**
     * @param ManagerRegistry $managerRegistry
     * @param RequestStack $requestStack
     * @param QueryCollectionExtensionInterface[] $collectionExtensions
     */
    public function __construct(ManagerRegistry $managerRegistry, RequestStack $requestStack, array $collectionExtensions = [])
    {
        $this->managerRegistry = $managerRegistry;
        $this->requestStack = $requestStack;
        $this->collectionExtensions = $collectionExtensions;
    }

    /**
     * @param string $resourceClass
     * @param string|null $operationName
     * @param array $context
     * @return bool
     */
    public function supports(string $resourceClass, string $operationName = null, array $context = []): bool
    {
        return DogBreed::class === $resourceClass;
    }

    /**
     * Retrieves a collection.
     *
     * @param string $resourceClass
     * @param string|null $operationName
     * @param array $context
     * @return array|\Traversable
     * @throws ResourceClassNotSupportedException
     */
    public function getCollection(string $resourceClass, string $operationName = null, array $context = [])
    {
        $manager = $this->managerRegistry->getManagerForClass($resourceClass);
        if (null === $manager) {
            throw new ResourceClassNotSupportedException();
        }

        $repository = $manager->getRepository($resourceClass);
        if (!method_exists($repository, 'createQueryBuilder')) {
            throw new RuntimeException('The repository class must have a "createQueryBuilder" method.');
        }

        $queryBuilder = $repository->createQueryBuilder('o');
        $queryNameGenerator = new QueryNameGenerator();
        foreach ($this->collectionExtensions as $extension) {
            $extension->applyToCollection($queryBuilder, $queryNameGenerator, $resourceClass, $operationName, $context);

            if ($extension instanceof QueryResultCollectionExtensionInterface && $extension->supportsResult($resourceClass, $operationName)) {
                $query = $queryBuilder->getQuery();
                $query->setHint(
                    Query::HINT_CUSTOM_OUTPUT_WALKER,
                    'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
                );
                // locale
                $query->setHint(
                    TranslatableListener::HINT_TRANSLATABLE_LOCALE,
                    $this->requestStack->getCurrentRequest()->getLocale() // take locale from session or request etc.
                );
                // fallback
                $query->setHint(
                    TranslatableListener::HINT_FALLBACK,
                    0 // fallback to default values in case if record is not translated
                );
                $query->setHint(TranslatableListener::HINT_INNER_JOIN, true);

                return $extension->getQueryResult($queryBuilder, $query);
            }
        }

        $query = $queryBuilder->getQuery();
//        $query->useQueryCache(false);
        $query->setHint(
            Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        // locale
        $query->setHint(
            TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            $this->requestStack->getCurrentRequest()->getLocale() // take locale from session or request etc.
        );
        // fallback
        $query->setHint(
            TranslatableListener::HINT_FALLBACK,
            0 // fallback to default values in case if record is not translated
        );
        $query->setHint(TranslatableListener::HINT_INNER_JOIN, true);
//        $query->setHydrationMode(TranslationWalker::HYDRATE_OBJECT_TRANSLATION);
//        $query->setHint(Query::HINT_REFRESH, true);

        return $query->getResult();
    }
}
```
Looking at the constructor of the doctrine Paginator shows that is transforming the queryBuilder into query, so this shouldn't make much of a difference. Allowing to use the query should overcome some limitations which the PaginatorExtension has if it only let get you results with the queryBuilder.

**Comment by soyuka** [comment]
Okay now I understand why you did that. Although this can't be merged, or we may want to introduce a new interface.

Here's how you could make it work with the current implementation:

```php
foreach ($this->collectionExtensions as $extension) {
    $extension->applyToCollection($queryBuilder, $queryNameGenerator, $resourceClass, $operationName, $context);

    // This is the last extension we will call
    if ($extension instanceof PaginationExtension && $extension->supportsResult($resourceClass, $operationName)) {
        $query = $queryBuilder->getQuery();
        $this->addTranslatableQueryHints();

        // Do the pagination again unless we can find a good solution here to reuse the code :|
        $doctrineOrmPaginator = new DoctrineOrmPaginator($query, $this->useFetchJoinCollection($queryBuilder));
        $doctrineOrmPaginator->setUseOutputWalkers($this->useOutputWalkers($queryBuilder));
        $resourceMetadata = null === $resourceClass ? null : $this->resourceMetadataFactory->create($resourceClass);
        if ($this->isPartialPaginationEnabled($this->requestStack->getCurrentRequest(), $resourceMetadata, $operationName)) {
                return new class($doctrineOrmPaginator) extends AbstractPaginator {
                };
        }

        return new Paginator($doctrineOrmPaginator);
    }
}

$query = $queryBuilder->getQuery();
$this->addTranslatableQueryHints();
return $query->getResult();
```

**Comment by soyuka** [comment]
Okay so, after seeing the work of @remoteclient on slack the main issue here is to use the Pagination in addition to another `QueryResultExtension` (extension that alters the Query). 
I've hit this in the past and I decided to not use the pagination at all but there are use case where this is needed.

I have two solutions in mind:

1. Don't use a Query Extension for pagination in the core but use another class that's being called when it needs to. 
2. Move the code responsible for the pagination in a reusable class (trait or public methods) so that one can re-use the following code without having to copy the whole class :

```
                // Do the pagination again unless we can find a good solution here to reuse the code :|
                $doctrineOrmPaginator = new DoctrineOrmPaginator($query, $this->useFetchJoinCollection($queryBuilder));
                $doctrineOrmPaginator->setUseOutputWalkers($this->useOutputWalkers($queryBuilder));
                $resourceMetadata = null === $resourceClass ? null : $this->resourceMetadataFactory->create($resourceClass);
                if ($this->isPartialPaginationEnabled($this->requestStack->getCurrentRequest(), $resourceMetadata, $operationName)) {
                    /** @var TYPE_NAME $doctrineOrmPaginator */
                    return new class($doctrineOrmPaginator) extends AbstractPaginator {
                    };
                }

                return new Paginator($doctrineOrmPaginator);
```

Indeed most of the methods there are `private`.

I though about extending the Pagination extension as well. As this would work only for collection, I think one would have to duplicate code. Not sure if it'd be best.

WDYT @api-platform/core-team ?

**Comment by dunglas** [comment]
👍 for the trait

**Comment by soyuka** [comment]
@dkarlovi I don't remember but someone had a similar issue on slack was it you? :smile:

**Comment by dkarlovi** [comment]
No. I did have the same growth opportunity, though. 😇

**Comment by soyuka** [comment]
Oh https://github.com/api-platform/core/issues/1802 we talked about pagination though :).

**Comment by dkarlovi** [comment]
I'm very :+1:  for extracting the limit/offset logic out of the pagination extension, as noted in #1802, yes. Trait seems OK.

**Comment by soyuka** [comment]
Closing this but let's keep discussing this in #1808

**Pull request closed without merging**
