### PR TITLE
Remove Composer authentication

### PR DESCRIPTION
**Pull request by theofidry**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none
| License       | MIT
| Doc PR        | none

As [GitHub removed their hourly API rate limit](https://github.com/composer/composer/issues/4884#issuecomment-195229989), we can remove this now.

### CODE REVIEW

**Comment by sroze** [comment]
:+1:

**Comment by sroze** [comment]
:tada:

**Comment by teohhanhui** [comment]
https://travis-ci.org/api-platform/core/jobs/115383910#L263

:disappointed:

**Comment by theofidry** [comment]
... :disappointed: worth to add a comment in the discussion thread I guess...

**Pull request merged**
