### PR TITLE
Fix issue in Required filter validator with dot notation

### LINKED ISSUE #4214: Filter\Validator\Require fails on nested property
**API Platform version(s) affected**: 2.6.0+

**Description**  
Hi, after upgrading v2.5.7 -> v2.6.4 I am facing the strange behaviour with required filter parameter on nested property. `QueryParameterValidator.php` (line 65) then returns `FilterValidationException: Query parameter "x.y" is required` even it is present in query and can work. 

Once the filter is set to be required i.e. in a custom filter, the `Filter\Validator\Require` class fails to test `requestHasQueryParameter()` when the parameter name contains dot (used for nested properties). This looks to be introduced in https://github.com/api-platform/core/pull/1723, where new `Require` class compares `$queryParameters` array in form "x.y" with result of `parse_str()` which converts dots to "x_y" (see e.g. https://stackoverflow.com/questions/68651/get-php-to-stop-replacing-characters-in-get-or-post-arrays) - this cannot match, then an exception is thrown. 

**How to reproduce**  

1. 
- Set Entity with nested property filter
- Create custom filter class, add `getDescription()` method with `'required' => true` like here https://api-platform.com/docs/core/filters/#creating-custom-filters
- Call API either directy or from ApiDoc
- `Filter\Validator\Require` complains on missing parameter?!

2.
- Set custom filter class with `'required' => false`
- `Filter\Validator\Require` test passes and filter works(!) 

**Possible Solution**  
Some workaround for `parse_str()` like here https://stackoverflow.com/questions/22539633/parse-string-containing-dots-in-php ?

Or compare output of `parse_str()` with  `$request->query->all()` which also has underscores instead of dots, as it is in v2.5.7 (https://github.com/api-platform/core/blob/37b5edf50cc05299b12cb8982be3efa035d726ce/src/Filter/QueryParameterValidateListener.php)

Or get underscores also in `$queryParameters`?

**Additional Context**  
`Require` class https://github.com/api-platform/core/pull/1723/files#diff-900c533383b3b17876e6a5c81e525632c8a492358f36f352b0db974e4d604a09

Test simple code
```
<?php
parse_str("x.y", $blabla);
var_dump($blabla);
```
which outputs
```
array(1) {
  ["x_y"]=>
  string(0) ""
}
```

### PR DESCRIPTION
**Pull request by jdeniau**
Fixes #4214

### CODE REVIEW

**Comment by alanpoulain** [comment]
Thank you! Don't you think it's a bugfix? It should target 2.6, isn't it?

**Comment by jdeniau** [comment]
@alanpoulain you are totally right 👍

**Comment by norkunas** [comment]
In Symfony there is `HeaderUtils::parseQuery`, maybe apip could use this in `RequestParser::parseRequestParams` ?

**Comment by guilliamxavier** [comment]
@norkunas: Symfony's `HeaderUtils::parseQuery` (which was actually partly inspired from API Platform's `RequestParser::parseRequestParams`) isn't available in Symfony < 5.2 (https://github.com/symfony/symfony/pull/37272)

**Comment by norkunas** [comment]
I know, but maybe it could fallback to it if available and later could be dropped from apip itself

**Comment by alanpoulain** [comment]
Yes it's possible to create a wrapper (and it's a good idea!), like we do for the Doctrine inflector: https://github.com/api-platform/core/blob/main/src/Util/Inflector.php.

**Comment by alanpoulain** [comment]
Anyway it can be done in another PR. Let's merge this one first. Could you add a changelog entry @jdeniau?

**Comment by jdeniau** [comment]
@alanpoulain done.

The CI fails for a reason that seems unrelated to my PR though. (some cache issue apparently)

**Review by alanpoulain — APPROVED** [review]

**Comment by alanpoulain** [comment]
Thank you @jdeniau.

**Comment by TheKassaK** [comment]
Hi, do you know when/how can I have this fix ? 

I'm on apiplatform 2.6.3

**Pull request merged**
