### PR TITLE
fix: do not use api_graphql_graphiql route when graphiQl is disabled because it won’t exist

### PR DESCRIPTION
**Pull request by MatTheCat**
| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | N/A
| License       | MIT
| Doc PR        | N/A

#5251 changed `SwaggerUi/index.html.twig` to always display a link to GraphiQL, but the `api_graphql_graphiql` route does not exist if `graphiQlEnabled` is `false`.

https://github.com/api-platform/core/blob/d0fcd70c34e79e1b072032a847b3a6e94f63db72/src/Symfony/Routing/ApiLoader.php#L141-L145

### CODE REVIEW

**Comment by alanpoulain** [comment]
Hello, thanks for this.
Could you add back the line:
```twig
{% if not graphQlEnabled %}<a href="javascript:alert('GraphQL support is not enabled, see https://api-platform.com/docs/core/graphql/')">GraphiQL</a>{% endif %}
```
Or maybe we don't want it anymore, @api-platform/core-team?

**Comment by MatTheCat** [comment]
@alanpoulain indeed missed that one, but it wasn’t consistent with the other link (also some others check the active UI).

**Comment by MatTheCat** [comment]
In that case shouldn’t it be the same for the GraphQL Playground link?

**Comment by alanpoulain** [comment]
> In that case shouldn’t it be the same for the GraphQL Playground link?

You mean checking the `active_ui`? I think you could add it too.

**Comment by alanpoulain** [comment]
GraphiQL is enabled by default, it's not the case for GraphQL Playground, so there is no need to add the alert for it.

**Comment by MatTheCat** [comment]
The default configuration seems to enable both `graphiql` and `graphql_playground`: https://github.com/api-platform/core/blob/d0fcd70c34e79e1b072032a847b3a6e94f63db72/src/Symfony/Bundle/DependencyInjection/Configuration.php#L229-L234

Am I missing something?

**Comment by MatTheCat** [comment]
Okay, PR updated!

**Comment by alanpoulain** [comment]
Thank you @MatTheCat.

**Comment by soyuka** [comment]
this should've been merge on 3.0

**Comment by MatTheCat** [comment]
The bug this PR fixes was introduced on the `main` branch though.

**Comment by soyuka** [comment]
oh right my bad thanks!

**Pull request merged**
