### PR TITLE
[Laravel] Graphql simple pagination fix "hasNextPage"

### LINKED ISSUE #6856: [Laravel] GraphQL Simple Pagination  "hasNextPage" error
**API Platform version(s) affected**: 4.0

**Description**  
Using GraphQL in laravel with simple pagination, generates docs for querying the field `hasNextPage`, but when you query it you get an error, since the laravel paginator implementation does not support it.

### PR DESCRIPTION
**Pull request by toitzi**
| Q             | A
| ------------- | ---
| Branch?       | 4.x
| Tickets       | Closes #6856
| License       | MIT
| Doc PR        | -

Also adds "currentPage" to graphql.

### CODE REVIEW

**Comment by soyuka** [comment]
Thanks @toitzi could you add a quick test at: https://github.com/api-platform/core/blob/main/src/Laravel/Tests/GraphQlTest.php?

**Comment by toitzi** [comment]
@soyuka Added a test for the page pagination (simple pagination)

**Comment by toitzi** [comment]
Sorry for the many forced pushs and updates, i cannot test locally the contributing.md guidline seems to be wrong / not working for me since composer global link is not a command, i will try to have a look into that and fix it, maybe you have an idea what i am missing

**Comment by soyuka** [comment]
`composer global require soyuka/pmu` ?

**Comment by toitzi** [comment]
For whatever reason, that does not work on my machine, probably an issue with my setup, i will try to fix it. Sorry in the meantime. Tests should now pass.

**Comment by soyuka** [comment]
No worries when you push it cancels the previous workflow. https://github.com/soyuka/pmu is used to link dependencies inside the monorepository.

**Comment by toitzi** [comment]
@soyuka the tests now pass, the phpstan error is because of some parrallel run, not because of this pr.

**Comment by soyuka** [comment]
yes I'm thinking about disabling the parallel execution...

**Pull request merged**
