### PR TITLE
fix: incorrect namespace

### PR DESCRIPTION
**Pull request by endroid**
| Q             | A
| ------------- | ---
| Branch?       | 4.0
| Tickets       | -
| License       | MIT
| Doc PR        | -

Fixes incorrect namespaces in new release.

### CODE REVIEW

**Comment by lchrusciel** [comment]
I've encountered the same issue when trying to test it out on @Sylius

**Review by dunglas — APPROVED** [review]
Good catch, thanks

**Comment by dunglas** [comment]
Thanks @endroid

**Comment by bnachtweh** [comment]
Thanks @endroid

**Pull request merged**
