### PR TITLE
Added support for pagination parameters in subresource docs

### PR DESCRIPTION
**Pull request by Toflar**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1812
| License       | MIT
| Doc PR        | not needed

This is the updated PR from https://github.com/api-platform/core/pull/1812. I'm sorry @RonRademaker I couldn't keep your commits separate and continue the work but instead I had to redo quite a bit because of the recent addition of OpenAPI Spec 3.0 support. I've made sure the commit is co-authored though so you get the attribution you deserve 😄 
Thanks for the initial work!

### CODE REVIEW

**Comment by Toflar** [comment]
Done at `EUFOSSA Hackathon`. Needs the label :)

**Comment by soyuka** [comment]
thanks @Toflar !

**Comment by alanpoulain** [comment]
No test for this feature?

**Comment by dunglas** [comment]
There is a functional test, right?

**Pull request merged**
