### PR TITLE
feat(metadata): use a custom Attribute extends ApiResource (#5076)

### PR DESCRIPTION
**Pull request by yobrx**
| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | #5076
| License       | MIT
| Doc PR        | 

Use a custom Attribute extending ApiResource class, see #5076 

```php
#[RestfulApi(
    routePrefix: '/live-chat',
)]
#[ORM\Entity]
class MyEntity
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private $id;

    public function __construct()
    {
    }

    public function getId()
    {
        return $this->id;
    }
}

```

```php
use ApiPlatform\Metadata\ApiResource;

#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
class RestfulApi extends ApiResource
{
    public function __construct(
        ?string $routePrefix = null,
    ) {
        parent::__construct(
            routePrefix: $routePrefix,
            normalizationContext: ['groups' => ['restful_read']],
            denormalizationContext: ['groups' => ['restful_write']],
            openapiContext: ['tags' => ['LiveChat']],
            order: ['id' => 'DESC'],
            security: 'is_granted("ROLE_OPERATOR")'
        );
    }
}
```

### CODE REVIEW

**Review by dunglas — APPROVED** [review]
LGTM!

**Comment by yobrx** [comment]
Wait, many behat tests are broken... :(

**Comment by soyuka** [comment]
This is nice thanks! I'm wondering if we shouldn't support this as a bug fix instead as it should've been possible on 3.0. Could you target 3.0?

**Comment by yobrx** [comment]
> This is nice thanks! I'm wondering if we shouldn't support this as a bug fix instead as it should've been possible on 3.0. Could you target 3.0?

Done !

**Comment by soyuka** [comment]
thanks @yobrx

**Pull request merged**
