### PR TITLE
Fix remove concat with more than 2 arguments

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #745 
| License       | MIT
| Doc PR        | ∅

### CODE REVIEW

**Comment by dunglas** [comment]
👍

**Comment by Simperfit** [comment]
👍

**Comment by dunglas** [comment]
WDYT @teohhanhui?

**Comment by teohhanhui** [comment]
@soyuka Since DQL does not support `CONCAT` for more than 2 arguments, I'm okay with reverting the relevant changes.

**Pull request closed without merging**
