### PR TITLE
Revert "Do not disable cache in dev"

### PR DESCRIPTION
**Pull request by teohhanhui**
Reverts api-platform/core#2629

See discussion in #2644

### CODE REVIEW

**Comment by soyuka** [comment]
I'm :+1: to keep this patch though (so :-1: on the revert :p)

**Comment by teohhanhui** [comment]
Hmm... See https://github.com/api-platform/core/issues/2644#issuecomment-476193238

**Comment by soyuka** [comment]
Yeah I saw the reasoning behind #2644 :). let's favor DX then but I still like this parameter being gone :P

**Comment by dunglas** [comment]
It would be nice to improve perf in dev, but it must not introduce DX regressions. It's probably possible to have a better dev cache strategy, in another PR.

**Comment by AristideHerveMbassi** [comment]
Please reopen because I have the same problem

**Pull request merged**
