### PR TITLE
Added the related symfony event to the EventPriorities class

### PR DESCRIPTION
**Pull request by lyrixx**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by soyuka** [comment]
They're also well documented here: https://api-platform.com/docs/core/events

**Comment by lyrixx** [comment]
I know I know. But I'm the kind of developer who prefer to read the code, than the doc ;)
(Even If I read the doc anyway :p)

But IMHO, it's *also* nice to have this doc in the code. It's really faster to open a class than a website.

**Comment by soyuka** [comment]
merged in https://github.com/api-platform/core/pull/1593

**Comment by soyuka** [comment]
Thanks @lyrixx

**Pull request closed without merging**
