### PR TITLE
Remove FilterEagerLoadingExtension when eager loading is disabled

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

Fix bug introduced in #950

/cc @soyuka

### CODE REVIEW

**Comment by soyuka** [comment]
Nice, should we keep injecting `forceEager` in the class then ([here](https://github.com/api-platform/core/pull/950/files#diff-84e5c2df62a8cf1ce1e759018f78674cR39))?

**Comment by teohhanhui** [comment]
@soyuka There's nothing wrong with that. :)

**Comment by soyuka** [comment]
Ok fine then, lmk if you want me to fix the tests :stuck_out_tongue:

**Comment by soyuka** [comment]
Tests fixed @dunglas this one too needs to go in the patch

**Comment by soyuka** [comment]
Thanks @teohhanhui !

**Pull request merged**
