### PR TITLE
optimization - don't normalize scalar data

### PR DESCRIPTION
**Pull request by SergeyMilegov**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| License       | MIT

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by soyuka** [comment]
tests would need a update, :+1: for the optimization though

**Comment by teohhanhui** [comment]
-1

It's a feature, not a bug. With the caching (Symfony 4.1 and #1988), there should not be any overhead after the first time anyway, if there's no normalizer registered for that particular property.

**Comment by soyuka** [comment]
> It's a feature, not a bug. With the caching (Symfony 4.1 and #1988), there should not be any overhead after the first time anyway, if there's no normalizer registered for that particular property.

We're still skipping some function calls no?

**Comment by teohhanhui** [comment]
This will break the use case of registering normalizers for scalar types. It just cannot work.

**Comment by bendavies** [comment]
@teohhanhui is right. this is why scalars are handled if a normalizer is not found: https://github.com/symfony/symfony/blob/a5a91d318ce73256b7c9677c3d46cf989383d006/src/Symfony/Component/Serializer/Serializer.php#L141

**Comment by dunglas** [comment]
I agree with @teohhanhui, 👎 on my side.

**Comment by SergeyMilegov** [comment]
>normalizers for scalar types...
WAT?
I made it to prevent normalization for scalar types because it is the most useless staff I can imagine.

**Comment by SergeyMilegov** [comment]
> It's a feature, not a bug. With the caching (Symfony 4.1 and #1988), there should not be any overhead after the first time anyway, if there's no normalizer registered for that particular property.
What if I am using symfony 3.3...

**Comment by teohhanhui** [comment]
@SergeyMilegov Normalizers for scalar types are not useless. Just because you don't use them, it doesn't mean that there are no valid use cases for them. :smile:

**Comment by SergeyMilegov** [comment]
>Normalizers for scalar types are not useless. Just because you don't use them, it doesn't mean that there are no valid use cases for them. smile

But how can I disable it if I don't need it?

**Comment by teohhanhui** [comment]
I think that's a good question. Do you have any suggestions? It'd be good to have in the Symfony Serializer too, I think.

**Comment by SergeyMilegov** [comment]
Symfony doesn't normalize properties: Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer::getAttributeValue
It is ApiPlatform's feature.
So you can add parameter to the config and apply my changes depends on this parameter.

**Comment by teohhanhui** [comment]
The AbstractObjectNormalizer is only an implementation. In fact, we could say that normalizing / denormalizing scalar values is a supported use case in Symfony Serializer, if we look at for example: https://github.com/symfony/symfony/blob/v4.1.0/src/Symfony/Component/Serializer/Serializer.php#L214

**Pull request closed without merging**
