### PR TITLE
WIP: Fix/router bridge match

### LINKED ISSUE #1006: Problem when specifying trusted_hosts
1. `Untrusted Host "localhost"` when fixing the `Request` for filters.
2. `Untrusted Host "schema.org"`, etc. (from external IRI) when calling `IriConverter::getItemFromIri`.

### PR DESCRIPTION
**Pull request by juferchaud**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | hope yes
| Fixed tickets | #1006
| License       | MIT
| Doc PR        | -

*Please update this template with something that matches your PR*

Ref https://github.com/api-platform/core/pull/ 1620 which description really fixes #1006 (same issue for me).

### CODE REVIEW

**Comment by soyuka** [comment]
unless it's a new feature, please target 2.3 thanks!

**Comment by juferchaud** [comment]
Behat does not pass in HAL features. I am not experienced enough to find why, sorry.

**Comment by juferchaud** [comment]
@soyuka Done ;)
Because Behat tests did not succeed, i have opened a second PR https://github.com/api-platform/core/pull/2150, trying fix #1006 with another way.

**Comment by Nek-** [comment]
@juferchaud maybe this PR can be close?

**Pull request closed without merging**
