### PR TITLE
minor: remove reference to .woff fonts-format

### PR DESCRIPTION
**Pull request by Chris53897**
https://github.com/api-platform/core/issues/5728

### CODE REVIEW

**Comment by soyuka** [comment]
isn't that a bug fix ?

**Comment by Chris53897** [comment]
yes, it is a minor fix. But only 5% of browsers are effected, and a wrong font is not so dramatic.
I just want to get rid of the warnings.

If you want, i can change the title. I have to look up how to change the commit message.

**Comment by soyuka** [comment]
We want to keep the older format for older  browsers I guess...

**Comment by Chris53897** [comment]
@soyuka ? The files do not exist in the repo.
If you want to add support of the woff format, the files need to be added in the first place.

**Comment by soyuka** [comment]
thanks!

**Pull request merged**
