### PR TITLE
Update Paths.php

### PR DESCRIPTION
**Pull request by abdounikarim**
| Q             | A
| ------------- | ---
| Branch?       | main for features / current stable version branch for bug fixes 
| Bug fix?      | no 
| New feature?  | no
| Deprecations? | no
| Tickets       | Fix #... 
| License       | MIT
| Doc PR        | api-platform/docs#...

### CODE REVIEW

**Comment by alanpoulain** [comment]
Hello, thanks for the PR. Could you add more context to your PR? Like describing a use case?

**Comment by abdounikarim** [comment]
Hello @alanpoulain , yep, of course. 
I think we can have an API in production and we don't want to give access to all routes (like hiding some routes which are for example still in dev or test mode), or if we want to give access only on a part of an API to users.

Does that answer to your question ? Cheers

**Comment by alanpoulain** [comment]
Thanks. @soyuka could you look at it?

**Comment by soyuka** [comment]
Sorry this doesn't fit the Immutable model of these classes, what about https://github.com/api-platform/core/pull/4099 to remove an operation?

**Comment by abdounikarim** [comment]
@soyuka we add more code 😛

**Pull request closed without merging**
