### PR TITLE
Document swagger-specific description options

### PR DESCRIPTION
**Pull request by greg0ire**
… and where to find them should there be newer ones.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes well at least I hope
| Fixed tickets | none
| License       | MIT
| Doc PR        | https://github.com/api-platform/docs/pull/322

### CODE REVIEW

**Comment by greg0ire** [comment]
@dunglas done

**Comment by dunglas** [comment]
Great! Thanks :D

**Comment by soyuka** [comment]
I think this should target 2.1 instead (as we targeted 2.1 in the docs)

**Comment by greg0ire** [comment]
@soyuka you're right, fixed!

**Comment by soyuka** [comment]
Thanks @greg0ire

**Pull request merged**
