### PR TITLE
fix #2115 SwaggerCommand with --yaml now properly serializes nested objects

### LINKED ISSUE #2115: [Swagger][Bug] swagger:export --yaml doesn't work as expected
If you use `--yaml`, the nested resources will not get dumped since they're not array but objects.

If I do:

```
        $content = $input->getOption('yaml')
            ? Yaml::dump(json_decode(json_encode($data), true))
            : json_encode($data, JSON_PRETTY_PRINT);
```

as a quick hack, it works as expected. Is this a bug in `Yaml` or should we workaround this here?

### PR DESCRIPTION
**Pull request by dkarlovi**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2115 
| License       | MIT

### CODE REVIEW

**Comment by dkarlovi** [comment]
CI failures unrelated.

**Comment by soyuka** [comment]
Do you see a way we could test this? I guess not really but we never know :p.

**Comment by dkarlovi** [comment]
Well sure, we add a sample couple of entities in the test suite and Swaggerize those? :)

**Comment by soyuka** [comment]
would be great!

**Comment by dunglas** [comment]
Thanks @dkarlovi

**Pull request merged**
