### PR TITLE
Draft: feat(normalizer): Add itemsPerPage for json-ld (hydra)

### PR DESCRIPTION
**Pull request by SiebeVE**
| Q             | A
| ------------- | ---
| Branch?       | 3.0
| Tickets       | /
| License       | MIT
| Doc PR        | /

Add the hydra:itemsPerPage property to the response of a json ld response.

### CODE REVIEW

**Comment by alanpoulain** [comment]
Hello, thanks for this PR however the [Hydra spec](https://www.hydra-cg.com/spec/latest/core/) does not define an `itemsPerPage` property.

**Comment by SiebeVE** [comment]
Mmh, I see, that is unfortunate 😄 .
What do you think of putting it in the `@context`?

**Comment by soyuka** [comment]
I think that you can compute that or probably create your subtype. Anyways we don't really want to implement things into the core that are not part of the specification.

**Comment by SiebeVE** [comment]
Okay, understandably, thanks for the consideration!

**Pull request closed without merging**
