### PR TITLE
Check code style of tests

### PR DESCRIPTION
**Pull request by theofidry**
Override [StyleCI default configuration](https://styleci.readme.io/docs/configuration) to include tests. They should be checked as well shouldn't they?

### CODE REVIEW

**Comment by theofidry** [comment]
Turns out there's an issue an StyleCI end. I reported it and they confirmed it, so waiting for them to provide a fix.

@sroze why that reaction?

**Comment by dunglas** [comment]
:+1:

**Comment by dunglas** [comment]
Thanks @theofidry

**Comment by theofidry** [comment]
@dunglas I think we should revert that one. The configuration is not working due to a bug in StyleCI, I didn't get any news from Graham since he told me he will look into it and provide a more powerful fixer.

**Comment by dunglas** [comment]
oops

**Comment by theofidry** [comment]
Well, it shouldn't break anything, luckily^^

**Pull request merged**
