### PR TITLE
hotfix: add an exception for item per page equal 0

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1118
| License       | MIT

### CODE REVIEW

**Comment by grachevko** [comment]
What if send negative number? :)

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-1 OFFSET 0' at line 1"
```

**Comment by Simperfit** [comment]
@soyuka done :)

**Comment by soyuka** [comment]
bug fix no? Shouldn't this target 2.0?

**Comment by dunglas** [comment]
@Simperfit you need to rebase ;)

**Pull request closed without merging**
