### PR TITLE
fix getClassType with no readableLink

### PR DESCRIPTION
**Pull request by Raulnet**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | [issue 3361](https://github.com/api-platform/core/issues/3361)
| License       | MIT
| Doc PR        | api-platform/docs#...

Fix condition

Additionally:
 - Always add tests and ensure they pass.
 - Never break backward compatibility.
 - Bug fixes should be based against the current stable version branch.
 - Features and deprecations must be submitted against master branch.
 - Legacy code removals go to the master branch.
 - Update CHANGELOG.md file.
-->

### CODE REVIEW

**Comment by dunglas** [comment]
Thanks @Raulnet!

**Comment by teohhanhui** [comment]
I don't think this is the right fix. The logic seems wrong to me.

**Comment by teohhanhui** [comment]
ping @dunglas @Raulnet

**Comment by soyuka** [comment]
I tend to agree it's "too simple to be true" ^^

**Comment by teohhanhui** [comment]
> "too simple to be true"

Well, I can confirm that it's wrong based on the condition.

**Pull request merged**
