### PR TITLE
Custom voters and request in the security expression

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1209
| License       | MIT
| Doc PR        | n/a

Allow to access to custom voters (new `is_granted` function) and to the current request in the security expression.

Can you try this patch @desmax?

TODO:

* [ ] Fix tests

### CODE REVIEW

**Comment by teohhanhui** [comment]
Can we also rename the `is_granted` attribute to `authorization`?

**Comment by dunglas** [comment]
@teohhanhui what do you think about `security` to keep in sync with the Symfony's controller annotation?

**Comment by teohhanhui** [comment]
[@Security](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/security.html) is a misnomer, when in fact it specifically deals with authorization. `access_control` could work though.

**Comment by dunglas** [comment]
`access_control` is consistent what is used in `security.yaml`, so go for this one.

**Pull request merged**
