### PR TITLE
feature: allow plain identifiers in json api

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1833
| License       | MIT
| Doc PR        | 

This PRs allows to use "allow_plain_identifiers" in JSON API.

### CODE REVIEW

**Comment by soyuka** [comment]
You should've asked first. This is joining my though in https://github.com/api-platform/core/pull/1716#issuecomment-379362006 

Using `ItemDataProvider` in the normalizers (this one or the abstract one) is wrong. We should only use `IriConverter`. This is even worse with #1478 because the `ItemDataProvider` needs to be called with normalized identifiers...
Also, `IriConverter` is the class we want to be responsible for handling data in the normalizers.

@Simperfit this is the fix I want to propose, I don't have much time though so feel free to do it :).

1. Add a method in `IriConverter` that has the following signature:

```
public function getIriFromPlainIdentifier($id, $resourceClass) {
 // returns an IRI
}
```

Or this alternative (not fond of this because `IriConverter` should only do things based on `IRIs`:
```
public function getItemFromPlainIdentifier($id, $resourceClass) {}
```

2. Use that IRI in the normalization processes
3. Rewrite a proper fix for #1716 related issue

**Comment by Simperfit** [comment]
Ow @soyuka I didn't know that was already a topic!

I can implement the first solution as it seem (to me too) to be the best one.

So I'm going to:
- remove ItemDataProvider from the abstract class.
- implement getIriFromPlainIdentifier and use it in the abstract class
- and use this new `getIriFromPlainIdentifier` in the JSONAPI's ItemNormalizer.

**Comment by dunglas** [comment]
You should create a new interface `PlainIdentifierConverterInterface` for that (it's not the responsibility of the `IriConverterInterface`).

**Comment by flug** [comment]
@Simperfit Up is this pull request still valid?

**Comment by soyuka** [comment]
Let's close this for now and keep track of it in #2686

**Pull request closed without merging**
