### PR TITLE
Do not eager join properties or associations that are not linked to a resource

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | api-platform/api-platform#179
| License       | MIT
| Doc PR        | 

https://github.com/api-platform/api-platform/issues/179

### CODE REVIEW

**Comment by dunglas** [comment]
@napalm33700 can you test this patch and report if it fixes your problem?

**Comment by dunglas** [comment]
@soyuka can you add a functional test to prevent regressions?

**Comment by napalm33700** [comment]
No more Resource not found error, but an another one Allowed memory size of XXXX bytes exhausted 

I will open a new issue

**Comment by teohhanhui** [comment]
Considering all the pitfalls, I'm for disabling "force_eager" by default (at least for v2).

ping @api-platform/core-team

**Comment by soyuka** [comment]
Coverage added

**Comment by dunglas** [comment]
@teohhanhui as it's now possible to disable this feature globally or per resource, I think it's ok to  let it enabled by default. Most people never change default settings... except when they got an error.

**Pull request merged**
