### PR TITLE
fix: do not log ValidationException

### PR DESCRIPTION
**Pull request by lyrixx**
Without this patch, the exception is not catched, and it processed by
the Symfony ErrorListener and a log message is processed. This is kind
of useless.

With this patch, the exeption is not logged anymore and is processed is
any other validation exception.

### CODE REVIEW

**Comment by alanpoulain** [comment]
Probably related to https://github.com/api-platform/core/issues/4216 and https://github.com/api-platform/core/issues/4214, don't you think?

**Comment by alanpoulain** [comment]
Could you add a unit test too please?

**Comment by lyrixx** [comment]
> Probably related to #4216 and #4214, don't you think?

I'm not sure. But I may be wrong :)

**Comment by alanpoulain** [comment]
I mean: since the filter validation only creates a log message, people are thinking that nested filtering is broken (https://github.com/api-platform/core/issues/4216) because they don't see the validation error (and the filter doesn't pass validation because of https://github.com/api-platform/core/issues/4214).

**Comment by lyrixx** [comment]
I added a unit test ✅

**Review by dunglas — APPROVED** [review]

**Comment by soyuka** [comment]
isn't this a bug fix?

**Comment by alanpoulain** [comment]
It could be a bugfix in `2.6` IMO.

**Comment by lyrixx** [comment]
What should I do? Should I rebase? just tell me :)

**Comment by alanpoulain** [comment]
Yes it would be nice if you could rebase it.

**Comment by lyrixx** [comment]
Done ✅

**Comment by alanpoulain** [comment]
Sorry it wasn't clear, I meant rebase agaisnt `2.6`. I've done it.

**Comment by alanpoulain** [comment]
Thank you @lyrixx.

**Pull request merged**
