### PR TITLE
Add doctrine/common to "require" block.

### PR DESCRIPTION
**Pull request by tuanphpvn**
Since ApiPlatform\Core\Metadata\Resource\Factory\AnnotationResourceMetadataFactory depend on Doctrine\Common.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by dunglas** [comment]
This dependency is optional (it's not mandatory to use annotations).

**Comment by tuanphpvn** [comment]
There are two things:

1. "it's not mandatory to use annotations" => Do you mean we can use xml or yaml? If so, since api_platform also support annotation. So doctrine/common is required.

2. "it's not mandatory to use annotations" => Just use annotation when use with symfony framework. So i think must have a directory separate in ```src/Metadata/Resource/Factory``` directory. Some kind like: 
src/Metadata/Symfony/Resource/Factory or src/Metadata/Zend/Resource/Factory. Correct if me wrong. Thanks.

**Comment by dunglas** [comment]
It's 1/ (you can use XML or YAML). And no it's not required, for instance: https://github.com/symfony/serializer/blob/master/composer.json#L28

**Comment by dunglas** [comment]
Check https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L190-L192

**Comment by tuanphpvn** [comment]
Using class but require register from outside package. Cool way!

**Pull request closed without merging**
