### PR TITLE
Rename metadata interfaces and classes

### LINKED ISSUE #420: [RFC] v2 metadata - confusing naming of interfaces and classes
The new names do not convey the correct semantics (a case of over-correcting for succinctness?) and are therefore highly confusing.

I propose the following changes:

| Current                                                           | Proposed                                      |
|-------------------------------------------------------------------|-----------------------------------------------|
| ...\Metadata\Property\CollectionMetadata                          | PropertyCollectionMetadata                    |
| ...\Metadata\Property\Factory\CollectionMetadataFactoryInterface  | PropertyCollectionMetadataFactoryInterface    |
| ...\Metadata\Property\Factory\ItemMetadataFactoryInterface        | PropertyMetadataFactoryInterface              |
| ...\Metadata\Property\ItemMetadata                                | PropertyMetadata                              |
| ...\Metadata\Resource\CollectionMetadata                          | ResourceCollectionMetadata                    |
| ...\Metadata\Resource\Factory\CollectionMetadataFactoryInterface  | ResourceCollectionMetadataFactoryInterface    |
| ...\Metadata\Resource\Factory\ItemMetadataFactoryInterface        | ResourceMetadataFactoryInterface              |
| ...\Metadata\Resource\ItemMetadata                                | ResourceMetadata                              |

(and relevant changes of the same fashion elsewhere)

Additional proposal for naming implementation classes:

| Current                                                               | Proposed                                      |
|-----------------------------------------------------------------------|-----------------------------------------------|
| ...\Metadata\Property\Factory\CollectionMetadataAnnotationFactory     | AnnotationPropertyCollectionMetadataFactory   |
| ...\Metadata\Property\Factory\ItemMetadataAnnotationFactory           | AnnotationPropertyMetadataFactory             |
| ...\Metadata\Property\Factory\ItemMetadataSerializerFactory           | SerializerPropertyMetadataFactory             |
| ...\Metadata\Resource\Factory\CollectionMetadataAnnotationFactory     | AnnotationResourceCollectionMetadataFactory   |
| ...\Metadata\Resource\Factory\ItemMetadataAnnotationFactory           | AnnotationResourceMetadataFactory             |
| ...\Metadata\Resource\Factory\ItemMetadataOperationFactory            | OperationResourceMetadataFactory              |
| ...\Metadata\Resource\Factory\ItemMetadataPhpDocFactory               | PhpDocResourceMetadataFactory                 |
| ...\Metadata\Resource\Factory\ItemMetadataShortNameFactory            | ShortNameResourceMetadataFactory              |

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #420
| License       | MIT
| Doc PR        | N/A

Resolves #420

Build is broken since symfony/symfony#17531

### CODE REVIEW

**Comment by teohhanhui** [comment]
Build with #433 - all Behat tests passing: https://travis-ci.org/teohhanhui/DunglasApiBundle/jobs/112816452

**Comment by dunglas** [comment]
:+1: looks good to me. Thanks for this tedious work.

**Comment by sroze** [comment]
@teohhanhui can you resolve the few remaining conflicts?

**Comment by teohhanhui** [comment]
Rebased and updated as per https://github.com/api-platform/core/issues/420#issuecomment-191817778

**Comment by dunglas** [comment]
Thank you very much @teohhanhui

**Comment by dunglas** [comment]
@teohhanhui can you rename services accordingly?

**Pull request merged**
