### PR TITLE
feat: Add compatibility with doctrine/orm 3.0

### PR DESCRIPTION
**Pull request by ddeboer**
| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | Closes api-platform/api-platform#2633
| License       | MIT
| Doc PR        | 

Introduce compatibility with doctrine/orm 3.0.

### CODE REVIEW

**Comment by soyuka** [comment]
nice! can you run the doctrine orm component tests? Also it looks like phpstan isn't happy

**Review by stevan-tosic — APPROVED** [review]

**Review by stevan-tosic — CHANGES_REQUESTED** [review]
All fine from my side but phpstan only to be resolved :)

**Comment by ddeboer** [comment]
Solved some problems, but others are popping up. Is there any documentation on how to run the tests and checks locally?

**Comment by soyuka** [comment]
Hi, thanks for the patch, I guess that our `lowest` tests would fail not having the new ClassMetadata? Still a bunch of red jobs though

**Comment by soyuka** [comment]
waiting for https://github.com/symfony/symfony/commit/ac07f3eb7842478d7ef736c8f280a1a16b7548e9

**Comment by fabpot** [comment]
@soyuka You need this commit in a release? If yes, which branch do you need (5.4, 6.4, 7.0, the three of them)?

**Comment by soyuka** [comment]
@fabpot yes 6.4 and 7.0 would be great but I'd like to be sure it's the only blocker

**Comment by soyuka** [comment]
Thanks @ddeboer fo  starting this went on my branch to continue as gh actions was buggy

**Comment by ddeboer** [comment]
My pleasure @soyuka. Thank you for wrapping this up.

**Pull request closed without merging**
