### PR TITLE
meta: missing throws doc property in the ReadListener

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Missing throws property on the phpdoc.

### CODE REVIEW

**Comment by soyuka** [comment]
php-cs-fixer

**Comment by Simperfit** [comment]
It is thrown at this point and it's not catched, it's possible to have the exception in here.

**Comment by meyerbaptiste** [comment]
So, you have to do the same for the 425 other places:

capture d ecran 2018-04-06 a 15 45 52

**Comment by Simperfit** [comment]
If we agree on this, I will do it, it seems better to me IMHO.

**Comment by soyuka** [comment]
> Do we really want this? I am in favor of only annotating exceptions that are explicitly thrown in our methods.

:+1: I don't see any advantage

**Comment by Simperfit** [comment]
Than ok ;) we can close this

**Pull request closed without merging**
