### PR TITLE
Add a cacheable no-op scalar normalizer

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2593 (partially)
| License       | MIT
| Doc PR        | N/A

/cc @bastnic

### CODE REVIEW

**Comment by teohhanhui** [comment]
Screenshots of Blackfire profiles, for comparison:

<details>
  <summary>without NoOpScalarNormalizer</summary>

  without NoOpScalarNormalizer

</details>

<details>
  <summary>with NoOpScalarNormalizer</summary>

  with NoOpScalarNormalizer

</details>

**Comment by bastnic** [comment]
nice! 

For the fun, did you try just moving the `is_scalar` test before the `getNormalizer` in `Serialier::normalize`.

**Comment by teohhanhui** [comment]
> For the fun, did you try just moving the is_scalar ... return check before the getNormalizer in Serialier::normalize?

No, we cannot do that. :)

**Comment by bastnic** [comment]
of course... at least with the current serializer implementation.

**Comment by soyuka** [comment]
This is good! Thanks @teohhanhui @bastnic

**Pull request merged**
