### PR TITLE
Fix wrong comment on kernel.request priority

### PR DESCRIPTION
**Pull request by teohhanhui**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by teohhanhui** [comment]
Or perhaps we should just remove this comment entirely, since it's not helpful...

**Comment by dunglas** [comment]
👍 (I find it helpful, I prefer to keep it)

**Comment by teohhanhui** [comment]
It should be moved to the entry above... :smile:

**Comment by dunglas** [comment]
Thanks @teohhanhui

**Pull request merged**
