### PR TITLE
GraphQL: Prevent an error when the type factory is null

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | MIT
| Doc PR        | n/a

Fixes a bug introduced by #2492.

### CODE REVIEW

**Comment by dunglas** [comment]
I don't understand. Either the constructor property isn't nullable, or we must add this test. Anyway there currently is a bug (and it's weird that PHPStan doesn't catch it).
I'm for allowing to pass null for this prop, because it makes it easier to reuse this class without Symfony DI.

**Comment by soyuka** [comment]
Also add to the graphql.xml definition `on-invalid=null`

**Comment by alanpoulain** [comment]
It's because I forgot to remove `= null`. I don't like to keep the previous code (it's not simply a `if`, GraphQL will not work if you don't set the `iterable` type). It means we had to add a deprecated. Same as here: https://github.com/api-platform/core/pull/2447#discussion_r248777048
IMO it's too much hassle for an experimental feature.

**Comment by dunglas** [comment]
> Also add to the graphql.xml definition `on-invalid=null`

Why? This case cannot happen.

> IMO it's too much hassle for an experimental feature.

It makes harder to use API Platform as a standalone lib. I don't get why we need to deprecate passing null, not everybody needs to add custom types. But I'm ok to remove the `=  null` as long a we fix the bug

**Comment by alanpoulain** [comment]
> I don't get why we need to deprecate passing null, not everybody needs to add custom types.
Sure, but we use the type factory for our needs too: to add the `Iterable` type (needed here: https://github.com/api-platform/core/blob/2bb6f950b4fe3568e5c87d3bbe56fbf87f1901da/src/GraphQl/Type/SchemaBuilder.php#L363).

**Comment by alanpoulain** [comment]
If you prefer, we can use the old behavior (https://github.com/api-platform/core/blob/22d350d95d592da7b3ee5117ac93e9f4e64b261f/src/GraphQl/Type/SchemaBuilder.php#L78) and only use the type factory for adding custom and non mandatory types.

**Comment by soyuka** [comment]
Just remove the `= null` in the constructor then? This class is experimental anyway no?

**Comment by dunglas** [comment]
Yes I'll update the pr

**Comment by dunglas** [comment]
As pointed (privately) by @meyerbaptiste, it's not the fault of Symfony.
The catch should be moved here: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/Router.php#L83

**Comment by soyuka** [comment]
tests must be updated

**Pull request merged**
