### PR TITLE
fix: use stateOptions when retrieving a Parameter filter

### LINKED ISSUE #6682: QueryParamter on DTO with stateOptions does not work
**API Platform version(s) affected**: 3.4.1

**Description**  
using `ApiFilter`, this works:
```php
#[ApiFilter(DateFilter::class, properties: ['birthday'])]
#[ApiResource(
    stateOptions: new Options(entityClass: Agent::class),
    shortName: 'Agent',
    operations: [
        new GetCollection(),

    ]
)]
class AgentApi
{
...
}
```

Trying to change this to `QueryParameter` does not work:
```php
#[ApiFilter(DateFilter::class, properties: ['birthday'], alias: 'app_filter_date')]
#[ApiResource(
    stateOptions: new Options(entityClass: Agent::class),
    shortName: 'Agent',
    operations: [
        new GetCollection(parameters: [
            'bla[:property]' => new QueryParameter(filter: 'app_filter_date'),
        ])
    ]
)]
class AgentApi
{
...
}
```

This is because `stateOptions` are not respected here:
https://github.com/api-platform/core/blob/3.4/src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php#L120
https://github.com/api-platform/core/blob/3.4/src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php#L245

I fixed these to respect stateOptions and it still didn't work (swagger ui was wrong)
so maybe other places need fixing?

**Possible Solution**  
respect `stateOptions`

### PR DESCRIPTION
**Pull request by vinceAmstoutz**
| Q             | A
| ------------- | ---
| Branch?       | `3.4`
| Tickets       | Closes #6682 
| License       | MIT

As mentioned in #6682, QueryParamter on DTO with `stateOptions` doesn't work. This PR will solve this problem by applying `stateOptions` to the `ParameterResourceMetadataCollectionFactory`.

### CODE REVIEW

**Comment by bendavies** [comment]
this doesn't seem to full work from what i can see/
the `hydra:template` looks correct and has `foo[before],foo[strictly_before],foo[after],foo[strictly_after]` etc...
but the swagger docs do not have 4 fields for `before`, `strictly_before` etc... do you know where this is done please @soyuka ?

**Comment by bendavies** [comment]
ok, actually, if you try to use a different property name on your entity to your resource class, like the following, the `hydra:template` is then incorrect and will just have `birthday` with no `[before]` etc...

```php

#[ORM\Entity]
class Agent
{
    #[ORM\Column]
    public ?\DateTimeImmutable $dob = null;

}
...

#[ApiFilter(DateFilter::class, properties: ['dob'], alias: 'app_filter_date')]
#[ApiResource(
    shortName: 'Agent',
    operations: [
        new GetCollection(parameters: [
            'birthday' => new QueryParameter(filter: 'app_filter_date'. property: 'dob'),
        ]),
    ],
    stateOptions: new Options(entityClass: Agent::class)
)]
class AgentApi
{
...
}
```

**Comment by soyuka** [comment]
[before] is a value of our parameter though it should not appear in the template?

**Comment by bendavies** [comment]
> [before] is a value of our parameter though it should not appear in the template?

yes, it should appear in the template as per this test:
https://github.com/api-platform/core/blob/fcd9a0725fb9fab942b306e5d3cb0e96226ee63e/tests/Functional/Parameters/DoctrineTest.php#L48

**Pull request merged**
